circle.yml

fixing circle command

---

src/shared/components/tc-communities/communities/tc-prod-dev/Learn/index.jsx

Reverts topcoder-platform/community-app#70

Revert "fix tests"

---

config/default.json
config/production.json
src/shared/components/TopcoderHeader/Auth/index.jsx
src/shared/components/TopcoderHeader/index.jsx
src/shared/components/tc-communities/AccessDenied/index.jsx
src/shared/components/tc-communities/AccessDenied/style.scss
src/shared/components/tc-communities/Footer/index.jsx
src/shared/components/tc-communities/Header/index.jsx
src/shared/components/tc-communities/JoinCommunity/index.jsx
src/shared/containers/Dashboard/index.jsx

- Proper SSO registration link
- Privacy policy link

Fixes for TopGear community

---

src/shared/components/challenge-listing/Filters/ChallengeSearchBar/index.jsx

Trim the query string before actual search

Fix issue #179: Search contest with keyword " ", no item show

---

src/shared/components/challenge-detail/Submissions/index.jsx
src/shared/components/challenge-detail/Winners/index.jsx
src/shared/containers/challenge-detail/index.jsx

fix issue #208

---

src/shared/components/challenge-listing/Tooltips/TrackAbbreviationTooltip/index.jsx

fix issue 182

---

src/shared/components/challenge-detail/Header/index.jsx

fixed #211 added $ for reliability bonus

fixed #221 added $ for reliability bonus

---

src/shared/components/challenge-listing/ChallengeCard/index.jsx

fixed #335 display platforms as tags in challenge card

fixed #335 display platforms as tags in challenge card

---

src/shared/components/challenge-detail/Header/style.scss

issue184 -iversonlv- No need of vertical parting line

---

src/shared/components/SubmissionManagement/Submission/index.jsx
src/shared/components/SubmissionManagement/SubmissionManagement/index.jsx
src/shared/components/SubmissionManagement/SubmissionsTable/index.jsx

fixes #348 hide delete submission buttons for past challenges

fixes #348 hide delete submission buttons for past challenges

---

src/shared/components/TopcoderHeader/desktop/SubMenu/Item/index.jsx
src/shared/components/challenge-listing/ChallengeCard/index.jsx

https://github.com/topcoder-platform/community-app/issues/166

Issue 166: Changed <a> header and challenge listing tags to <Link>

---

src/shared/components/TopcoderHeader/style.scss
src/shared/components/challenge-detail/Header/style.scss

Issue194 -iversonLv- Search overlap with the filter section

---

src/shared/components/challenge-detail/Header/DeadlineCards.jsx
src/shared/components/challenge-detail/Header/index.jsx
src/shared/components/challenge-detail/Header/style.scss

fix issue #207

---

src/shared/components/challenge-detail/Header/index.jsx
src/shared/components/challenge-detail/Header/style.scss

fixed #172 replaced text for completed challenges

fixed #172 replaced text for completed challenges

---

src/shared/components/challenge-listing/Filters/FiltersPanel/index.jsx

fixed #216 disabled save button for empty filters

fixed #216 disabled save button for empty filters

---

src/shared/components/challenge-listing/Listing/index.jsx
src/shared/components/challenge-listing/index.jsx

fixed #198 filter list overlap issue

fixed #198 filter list overlap issue

---

src/shared/components/challenge-listing/Tooltips/UserAvatarTooltip/style.scss

fixed #251 tooltip image profile layout

fixed #251 tooltip image profile layout

---

src/shared/components/challenge-detail/Header/Prizes.jsx

fixed #290 formatting of prizes in header

fixed #290 formatting of prizes in header

---

src/shared/components/challenge-detail/Header/style.scss

fixed #253 padding for bonus text

fixed #253 padding for bonus text

---

src/shared/components/challenge-detail/Header/Prizes.jsx

fixed #296 hide 0 value prizes in design f2f

fixed #296 hide 0 value prizes in design f2f

---

src/shared/components/challenge-detail/Header/index.jsx

fixed #292 added registration deadline and logiin for next deadline

fixed #292 added registration deadline and logiin for next deadline

---

src/shared/components/challenge-detail/Specification/styles.scss

fixed #298 set max width for images in challenge details

fixed #298 set max width for images in challenge details

---

src/shared/components/challenge-detail/Specification/styles.scss

fixed #300 code formatting in challenge details

fixed #300 code formatting in challenge details

---

src/shared/components/challenge-listing/Filters/_fix_DateInput__input.css

fixed #276 keyboard shortcut icon styles

fixed #276 keyboard shortcut icon styles

---

src/shared/components/challenge-detail/Winners/index.jsx

fixed #254 challenge details winner missing

fixed #254 challenge details winner missing

---

src/shared/components/challenge-listing/ChallengeCard/index.jsx

fix issue #281

---

src/shared/components/TopcoderHeader/style.scss

issue361 -iversonLv- Search inpu at search flyout not vertical

---

src/shared/components/challenge-listing/Filters/EditTrackPanel/index.jsx

fixed #381 stylings for data science trrack text

fixed #381 stylings for data science trrack text

---

src/shared/components/challenge-detail/Winners/index.jsx

fixed #368 hide download link in locked submissions

fixed #368 hide download link in locked submissions

---

src/shared/components/TopcoderHeader/mobile/Header/style.scss

PR for issue383 -iversonLv- Mobile :Join button overlapping on Menu

---

src/shared/components/challenge-detail/Registrants/index.jsx

fixed #380 submitted header label in mobile devices correction

fixed #380 submitted header label in mobile devices correction

---

src/shared/components/challenge-listing/Filters/FiltersPanel/index.jsx

Issue #384

---

src/shared/components/challenge-listing/ChallengeCard/Prize/style.scss

PR for issue373 -iversonLv- Be consistent in displaying the prize monty

---

src/shared/components/challenge-listing/Filters/FiltersPanel/style.scss

Fix issue #382

---

src/shared/components/challenge-detail/Submissions/style.scss

fixed #260 reduced margin for 4 cols

fixed #260 reduced margin for 4 cols

---

src/shared/components/challenge-detail/Submissions/index.jsx

fixed #258 removed redundant part from url

fixed #258 removed redundant part from url

---

src/shared/components/SubmissionManagement/SubmissionManagement/index.jsx

fixed #349 challenge over text in my-submissions

fixed #349 challenge over text in my-submissions

---

src/shared/components/challenge-listing/ChallengeCard/Prize/style.scss

fixed #367 change purse tag to inline

fixed #367 change purse tag to inline

---

src/shared/components/challenge-listing/Sidebar/FiltersEditor/Item/style.scss

PR for issue388 -iversonLv- Inconsistency in Tooltip UI for Delete Filter

---

__tests__/shared/components/challenge-listing/Filters/__snapshots__/ChallengeFilters.jsx.snap
src/shared/components/challenge-listing/Filters/ChallengeFilters.jsx
src/shared/components/challenge-listing/Filters/ChallengeFilters.scss

1) Implemented as suggested
2) Because expected UI is changed, I have to update the test case file __tests__/shared/components/challenge-listing/Filters/__snapshots__/ChallengeFilters.jsx.snap to pass the 'npm test'

Fix Issue 376

---

src/shared/components/challenge-detail/Checkpoints/index.jsx
src/shared/components/challenge-detail/Checkpoints/styles.scss

fixed #242 empty feedback text

fixed #242 empty feedback text

---

src/shared/components/challenge-detail/Header/TabSelector/index.jsx
src/shared/components/challenge-detail/Header/index.jsx

fixed #191 added check for hasregistered for showing forum link

fixed #191 added check for hasregistered for showing forum link

---

src/shared/components/buttons/default.scss

fixed #175 styles for default button

Issue #175

---

src/shared/actions/challenge-listing/sidebar.js
src/shared/components/challenge-listing/Filters/ChallengeFilters.jsx
src/shared/components/challenge-listing/Filters/FiltersPanel/index.jsx
src/shared/containers/challenge-listing/FilterPanel.jsx
src/shared/reducers/challenge-listing/sidebar.js

This is pretty straight forward. Just a new redux state for storing whether or not a new filter is currently being saved. If it is being saved, we disable the save filter button.

Filter with duplicate name #196

---

__tests__/shared/components/challenge-listing/Filters/__snapshots__/DateRangePicker.jsx.snap
__tests__/shared/components/challenge-listing/Filters/__snapshots__/FiltersPanel.jsx.snap
package-lock.json
src/shared/components/challenge-listing/Filters/DateRangePicker.jsx

New branch with issue fix

---

src/shared/components/tc-communities/AccessDenied/style.scss
src/shared/containers/SubmissionManagement/index.jsx
src/shared/containers/SubmissionPage.jsx

fixes #515 unauthorized error for unregistered and anon users

Issue 515 submit pages

---

src/shared/routes/Communities/Blockchain/Routes.jsx
src/shared/routes/Communities/Community2/Routes.jsx
src/shared/routes/Communities/DemoExpert/Routes.jsx
src/shared/routes/Communities/QA/Routes.jsx
src/shared/routes/Communities/SRMx/Routes.jsx
src/shared/routes/Communities/TaskForce/Routes.jsx
src/shared/routes/Communities/TcProdDev/Routes/index.jsx
src/shared/routes/Communities/Veterans/Routes.jsx

Challenge listing (at least in blockchain community) redirects to challenge details pages on main www.topcoder.com domain

#583 Challenge listing redirection

---

src/shared/actions/challenge.js
src/shared/components/challenge-detail/Header/TabSelector/index.jsx
src/shared/components/challenge-detail/Header/TabSelector/style.scss

Tabs selector on challenge details page should be blue for all types of challenges

#621 Tabs selector on challenge details page should be blue

---

src/shared/components/tc-communities/Dropdown/index.jsx
src/shared/components/tc-communities/Dropdown/style.scss
src/shared/containers/tc-communities/CommunityStats.jsx
src/shared/containers/tc-communities/Header.jsx

There is no url in returned community list, so I assume the url for each community is`/community/${communityId}`.

#587 Update communities dropdown in header to be dynamic

---

src/shared/components/Terms/index.jsx
src/shared/containers/terms-detail/index.jsx
src/shared/containers/terms-detail/styles.scss
src/shared/reducers/terms.js
src/shared/routes/TermsDetail.jsx
src/shared/routes/Topcoder/Routes.jsx
src/shared/services/terms.js

basic terms: <http://local.topcoder-dev.com:3000/challenges/terms/detail/21193>
doc sign terms: <http://local.topcoder-dev.com:3000/challenges/terms/detail/21153>
not found terms: <http://local.topcoder-dev.com:3000/challenges/terms/detail/123>

#607, Basic Terms Page

---

src/shared/components/challenge-detail/Header/index.jsx

Removed the ThemeProvider and related code

[$50] - Challenge details header: standard buttons styling #641

---

src/shared/components/TopcoderFooter/style.scss

refined styles for the spacing on the footer...

[$100] - Restyle the standard TC footer #692

---

src/shared/components/Terms/TermDetails.scss
src/shared/components/Terms/index.jsx
src/shared/components/Terms/styles.scss
src/shared/containers/Terms.jsx
src/shared/containers/challenge-detail/index.jsx

couldn't mock the page properly to test.
Therefore, all the requirements on the ticket are not completed.

[$100] - NDA differences between design and development #647

---

src/shared/containers/challenge-listing/Sidebar.jsx

I was able to append the fake first element in the render function of the underlying component, as opposed to appending it in the `mapStateToProps` function. Fixes #649

[$50] - Fix performance bug in sidebar nav #649

---

src/shared/components/challenge-listing/Filters/FiltersPanel/style.scss

Center close icon in subtrack select value in filter panel

---

src/shared/containers/challenge-listing/Listing/index.jsx

Fix proptype validation

---

src/shared/components/LoadingIndicator/index.jsx

This minor PR removes a comment added in [this commit](https://github.com/topcoder-platform/community-app/commit/de647fcd465aeb626431d9aca19856ba802f9b65) which is no longer relevant.

Remove irrelevant old comment

---

__tests__/shared/components/TopcoderHeader/mobile/__snapshots__/Search.jsx.snap
src/shared/components/TopcoderHeader/mobile/Search/index.jsx
src/shared/components/TopcoderHeader/mobile/Search/style.scss

- Vertically centers search icon in Mobile searchbar
- Adds `aria-label` to search input field to improve accessibility

Enhancements to mobile member searchbar

---

__tests__/shared/components/challenge-listing/Filters/__snapshots__/FiltersPanel.jsx.snap
src/shared/components/challenge-listing/Filters/FiltersPanel/index.jsx

Use unique ids for date range pickers(one month and two months)

Fix duplicate ids

---

src/shared/components/TopcoderFooter/style.scss
src/shared/components/TopcoderHeader/style.scss
src/shared/routes/Topcoder/styles.scss

Used a fix described here: https://github.com/philipwalton/solved-by-flexbox/blob/master/assets/css/components/site.css

#612 Fixed styling for IE 11

---

src/shared/components/challenge-listing/Tooltips/TrackAbbreviationTooltip/index.jsx

Fix minor typo

---

src/shared/components/Settings/Account/MyAccount/styles.scss
src/shared/components/Settings/Tools/Subscriptions/styles.scss

Profile Settings - button text wrapping fixed

Issue #1156: Profile Settings - button text wrapping

---

src/shared/components/ProfilePage/Stats/ChartTooltip/index.jsx
src/shared/components/ProfilePage/Stats/HistoryGraph/index.jsx

Fix for #1048   
Clicking the challenge name in the graph popup should now lead to the challenge details page.

Issue #1048

---

src/shared/components/ProfilePage/Stats/HistoryGraph/index.jsx

fixed #1047
make sure Tool tip prompt was disappear when leave the page

Fix Ticket #1047 

---

src/shared/components/Settings/Profile/Skills/index.jsx
src/shared/containers/Settings.jsx
src/shared/reducers/page/settings.js

update the logic of that page to save the skills in the same way as the legacy app (https://github.com/appirio-tech/topcoder-app/).

Fix issue #1167

---

src/shared/components/ChallengeTile/style.scss

- Fix winner ribbon from overlapping

Issue #1175: Profile - user challenges style issue

---

src/shared/components/Settings/Account/LinkedAccount/modal.scss

Profile - Style issue when deleting a long link #1177

fix issue #1177

---

src/shared/utils/memberStats.js

Percentage is now rounded to 2 decimals

---

src/shared/components/SRMTile/style.scss

Fix for issue #977 
Fix alignment issue on the past SRM page.

Fix alignment issue

---

__tests__/shared/components/ProfilePage/__snapshots__/index.jsx.snap
src/shared/components/ProfilePage/index.jsx

fix issue #959
Remove the View other members button as the page doesn't exist anymore.

fix issue #959

---

src/shared/components/ProfilePage/Stats/HistoryGraph/index.jsx

fix issue #1055
Chrome-Mobile-Member, Graph is not completely displayed

fix issue #1055

---

src/shared/components/Settings/Account/LinkedAccount/styles.scss

fix issue #956
fix External Link text box is overlap the beneath list

fix issue #956

---

src/shared/components/ProfilePage/Stats/DistributionGraph/index.jsx

fix issue #1191
Profile - The rating distribution graph is not completely shown on mobile

fix issue #1191 rating distribution graph

---

src/shared/components/Settings/Profile/Hobby/styles.scss

Fix Profile - Hobby - Textarea resize issue

---

package.json
src/shared/containers/Profile.jsx

fix issue #1192
Profile - Issue when visiting another member's profile
clear profile before loading profile
pls check https://github.com/topcoder-platform/topcoder-react-lib/pull/21 first

fix issue #1192 Issue when visiting another member

---

src/shared/components/Settings/Profile/Skills/index.jsx
src/shared/components/Settings/Profile/Skills/styles.scss

Please see description here -> https://github.com/topcoder-platform/community-app/issues/1223
- Only show the skills under the Your skills section
- Reduce the bottom margin of each skill to 55px

Issue 1223:  Profile - Fixes on the skills page

---

src/shared/components/Settings/Profile/Community/data.jsx
src/shared/components/Settings/Profile/Community/index.jsx

remove IOS and Predix communities

fixed issue #1230: Profile - remove some communities

---

src/shared/components/Settings/Profile/BasicInfo/index.jsx

First name last name and country is mandatory rest all are optional

issue_1108 fixed basic info form validations

---

src/shared/components/SubmissionPage/FilestackFilePicker/index.jsx
src/shared/components/SubmissionPage/Submit/index.jsx
src/shared/components/SubmissionPage/index.jsx
src/shared/containers/SubmissionPage.jsx
src/shared/routes/Communities/Wipro/Routes.jsx

fix issue #1268 -> Set only url source for submission picker of topgear group

fix issue #1268 -> Set only url source for submission picker of topgear

---

src/shared/components/SubmissionPage/FilestackFilePicker/index.jsx
src/shared/components/SubmissionPage/Submit/index.jsx
src/shared/components/SubmissionPage/index.jsx
src/shared/containers/SubmissionPage.jsx
src/styles/_global/_forms.scss

ignore loading group list if challenge don't belong to any group and adding loading indicator if the group haven't loaded yet
original issue: #1268

#1268 add ignore loading group and loading indicator 

---

src/shared/components/SubmissionPage/FilestackFilePicker/index.jsx
src/shared/components/SubmissionPage/FilestackFilePicker/styles.scss
src/shared/components/SubmissionPage/Submit/index.jsx

implement input box for URL issue #1268

implement input box for URL issue #1268

---

src/shared/components/ProfilePage/Stats/ChartTooltip/index.jsx
src/shared/components/ProfilePage/Stats/HistoryGraph/index.jsx
src/shared/components/ProfilePage/Stats/index.jsx

Issue 1288 - Fix URL in MM and SRM rating graph tooltip

---

src/shared/components/Settings/Tools/Software/styles.scss

Fixed issue #1324

---

.gitignore
src/shared/components/Settings/Profile/Skills/index.jsx

Fix Issue #1473

---

src/shared/components/Settings/Account/MyAccount/index.jsx
src/shared/components/Settings/Account/MyAccount/styles.scss

Fix for Issue# 1450

---

src/shared/components/Settings/Account/LinkedAccount/styles.scss

fix issue #1344

---

src/shared/actions/page/settings.js
src/shared/components/Settings/Account/index.jsx
src/shared/components/Settings/Preferences/index.jsx
src/shared/components/Settings/Profile/index.jsx
src/shared/components/Settings/Tools/index.jsx
src/shared/containers/Settings.jsx
src/shared/reducers/page/settings.js

fix issue #1330

---

src/shared/routes/index.jsx

Fix for Issue #1544

---

package.json

To justify my solution , 
following are the links of discussion which shall be referred in sequence as follows:
1.https://github.com/JedWatson/react-select/issues/2182
2.https://github.com/JedWatson/react-select/pull/2213

issue_1501 fixed

---

src/shared/components/Settings/Profile/BasicInfo/ImageInput/index.jsx

fix issue #1352

---

src/shared/components/Settings/Account/MyAccount/index.jsx
src/shared/components/Settings/Account/MyAccount/styles.scss

fix issue #1452

---

src/shared/components/Settings/Account/MyAccount/index.jsx

fix issue #1454

---

src/shared/components/Settings/Profile/BasicInfo/styles.scss
src/shared/components/Settings/Profile/Hobby/styles.scss

fix issue #1465

---

src/shared/reducers/page/settings.js

fix issue #1484

---

src/shared/components/Settings/Profile/Skills/index.jsx

fix issue #1486

---

src/assets/images/tools/service-provider-types/Television.svg

Updated Television icon

---

src/server/routes/mailchimp.js

Fix Issue #1600

---

src/shared/components/Settings/Profile/Skills/index.jsx

Filter out the skills that are already in the members profile.

---

src/shared/components/Settings/Account/LinkedAccount/AddWebLink.jsx

Fixed regex for url check

---

src/shared/components/Settings/style.scss
src/styles/_mixins/_typography.scss

Changed drop down text style at given page and all sub pages

issues-1326: changed drop down text style

---

src/shared/components/Settings/Account/MyAccount/index.jsx

renamed 'Create New Email' to 'New Email'

issues-1453: renamed 'Create New Email'

---

src/server/services/avatar.js
src/shared/components/Settings/Profile/BasicInfo/ImageInput/index.jsx

fix issue #1364
@ThomasKranitsas this is fix code to cdn public server.
the server convert image to jpeq, please re-deploy the server with my code for testing

fix issue #1364

---

src/shared/components/Settings/Preferences/Email/index.jsx

issues-1449: made both label to E-Mail

---

src/shared/components/Settings/Account/MyAccount/styles.scss

Added `border-bottom` to fix the problem

issues-1446: fix css

---

src/shared/components/Settings/Profile/BasicInfo/index.jsx
src/shared/components/Settings/Profile/BasicInfo/styles.scss
src/shared/components/challenge-listing/Filters/DatePicker.jsx
src/shared/components/challenge-listing/Filters/_fix_SingleDatePicker.css

Added Date picker and use at Birth Date
Look of the date picker is now uniform across browsers. And at Edge in windows it's looks like this:

issues-1305: Added Date picker and use at Birth Date

---

src/shared/components/Settings/Account/LinkedAccount/AddWebLink.jsx

fix issue #1436

---

src/shared/components/Settings/Tools/Subscriptions/index.jsx
src/shared/components/Settings/Tools/Subscriptions/styles.scss

Fix for issue #1463 
Now the button has equal spaces from the top and bottom in IE11

Fix add subscription button layout in IE11

---

src/shared/components/Settings/Account/LinkedAccount/styles.scss

fix issue #1427

---

src/shared/components/Settings/Profile/Skills/index.jsx

fix issue #1478

---

src/shared/components/Contentful/ContentSlider/ContentSlider.jsx

fix issue #1262

---

__tests__/shared/components/Settings/Profile/AboutMe/__snapshots__/index.jsx.snap
__tests__/shared/components/__snapshots__/Select.jsx.snap
__tests__/shared/components/challenge-listing/Filters/__snapshots__/FiltersPanel.jsx.snap
src/shared/components/Select/index.jsx
src/shared/components/Settings/Profile/Skills/index.jsx

fix issue #1476

---

src/shared/components/Looker/index.jsx
src/shared/components/SubmissionPage/Submit/index.jsx
src/shared/components/examples/Looker/index.jsx

Fix for issue #1657

---

src/shared/components/Looker/index.jsx
src/shared/components/examples/Looker/index.jsx

Fix for issue #1669

---

src/shared/components/Settings/Account/MyAccount/index.jsx
src/shared/components/Settings/Account/MyAccount/styles.scss

Using the same style as `Password`. Now its look the same:

issues:1685: Changed style of New password field

---

config/default.js
src/shared/services/contentful.js

Fix for issue #1695

---

src/shared/components/Settings/Account/LinkedAccount/styles.scss

Reduced the opacity if disabled

issues:1336 - Reduced the opacity if disabled

---

src/shared/reducers/page/settings.js

Fix for Issue #1306

---

src/shared/components/Settings/Profile/Community/index.jsx

Fix for issue #1378

---

package-lock.json
package.json

The only build error I got locally for 
`npm run build:dev`
`npm run build`
is `Error: Can't resolve 'filestack-js'`
After adding filestack-js library, the build works.

Add filestack-js library

---

src/shared/components/SubmissionPage/index.jsx

Reverts topcoder-platform/community-app#1747

Revert "issue_1743 fixed"

---

src/shared/components/challenge-listing/ChallengeCard/Status/index.jsx

Fix for issue #1738

---

src/shared/components/challenge-detail/Header/ChallengeTags.jsx
src/shared/components/challenge-listing/ChallengeCard/index.jsx

Fix for issue #1754

---

src/shared/components/Settings/Profile/BasicInfo/index.jsx

fix issue #1520

---

src/shared/components/Settings/Profile/BasicInfo/index.jsx

Fixed issue #1767

---

src/shared/components/challenge-detail/Submissions/SubmissionRow/SubmissionHistoryRow/index.jsx

Fix for issue #1778

---

src/shared/components/challenge-detail/Submissions/SubmissionRow/SubmissionHistoryRow/index.jsx

Reverts topcoder-platform/community-app#1779
Dint fix the issue

Revert "Fix for issue #1778"

---

src/shared/components/challenge-detail/Submissions/SubmissionRow/SubmissionHistoryRow/index.jsx

https://github.com/topcoder-platform/community-app/issues/1778

Fixed score mapping issue

---

src/shared/components/Dashboard/Announcement/index.jsx
src/shared/components/Dashboard/Announcement/style.scss
src/shared/components/SubmissionPage/Submit/index.jsx
src/shared/components/challenge-detail/Header/TabSelector/index.jsx
src/shared/components/challenge-detail/Header/index.jsx
src/shared/components/tc-communities/Header/index.jsx
src/shared/components/tc-communities/communities/zurich/theme/header.scss

Reverts topcoder-platform/community-app#1805
@sushilshinde fyi

Revert "Hot fixes"

---

src/shared/components/SubmissionPage/Submit/index.jsx

Reverts topcoder-platform/community-app#1804

Revert "Fix for topgear submission filestack issue"

---

src/shared/components/SubmissionPage/Submit/index.jsx

Reverts topcoder-platform/community-app#1798

Revert "issue_1775 fixed"

---

src/shared/components/challenge-listing/Filters/ChallengeFilters.jsx

log for issue #1816 
Let's log and see how deployed env is behaving since it works fine locally in prod mode too. We will revert this once tested.

Issue #1816 : log filterstate

---

__tests__/shared/components/challenge-listing/__snapshots__/index.jsx.snap
src/shared/components/challenge-listing/index.jsx

fix no filterState being passed to ChallengeFilters

Issue #1816

---

src/shared/components/challenge-listing/Filters/ChallengeFilters.jsx

Reverts topcoder-platform/community-app#1831

Revert "Issue #1816 : log filterstate"

---

__tests__/shared/components/__snapshots__/TopcoderFooter.jsx.snap
__tests__/shared/components/challenge-listing/Sidebar/__snapshots__/Footer.jsx.snap
src/shared/components/challenge-detail/Submissions/index.jsx

Sorting on submissions/leaderboard on challenge page #1851

Sorting on submissions/leaderboard on challenge page #1851

---

src/shared/components/challenge-detail/Submissions/style.scss

Reverts topcoder-platform/community-app#1863

Revert "issue1786 handles css patch fix"

---

src/shared/components/challenge-detail/Submissions/index.jsx
src/shared/components/challenge-detail/Submissions/style.scss

Reverts topcoder-platform/community-app#1852

Revert "Issue 1786 fixed"

---

src/shared/components/challenge-listing/Filters/DatePicker.jsx

@ThomasKranitsas Please review it

Fix birth date input on the settings page

---

src/shared/containers/challenge-listing/FilterPanel.jsx

Challenge List Filter Issue #1816

Challenge List Filter Issue #1816

---

src/shared/containers/SubmissionPage.jsx
src/shared/containers/challenge-detail/index.jsx
src/shared/containers/challenge-listing/Listing/index.jsx

Reverts topcoder-platform/community-app#1881

Revert "Fix issue with fetching communities list"

---

src/shared/components/Contentful/ContentBlock/themes/zurich.scss
src/shared/components/Contentful/Tabs/themes/tabsGroupChildren.scss
src/shared/components/Contentful/Tabs/themes/zurich.scss

Catalog page not rendering well on ie 11 #1915

Catalog page not rendering well on ie 11 #1915

---

package-lock.json
package.json
src/shared/containers/challenge-listing/Listing/index.jsx

Reverts topcoder-platform/community-app#1925

Revert "Upgrade topcorder-react-lib"

---

src/shared/utils/memberStats.js

https://github.com/topcoder-platform/community-app/issues/1942

Add rating details in Code track

---

.circleci/config.yml
__tests__/shared/actions/challenge-listing/index.js
__tests__/shared/components/challenge-listing/Listing/__snapshots__/index.jsx.snap
__tests__/shared/components/challenge-listing/Listing/index.jsx
__tests__/shared/components/challenge-listing/Sidebar/BucketSelector/Bucket.jsx
__tests__/shared/components/challenge-listing/Sidebar/BucketSelector/__snapshots__/Bucket.jsx.snap
__tests__/shared/components/challenge-listing/Sidebar/BucketSelector/__snapshots__/index.jsx.snap
__tests__/shared/components/challenge-listing/Sidebar/BucketSelector/index.jsx
__tests__/shared/components/challenge-listing/__snapshots__/index.jsx.snap
__tests__/shared/containers/challenge-listing/Sidebar.jsx
__tests__/shared/reducers/challenge-listing/index.js
package-lock.json
src/shared/actions/challenge-listing/index.js
src/shared/components/challenge-listing/Listing/Bucket/index.jsx
src/shared/components/challenge-listing/Listing/index.jsx
src/shared/components/challenge-listing/Sidebar/BucketSelector/Bucket/index.jsx
src/shared/components/challenge-listing/index.jsx
src/shared/containers/challenge-listing/Listing/index.jsx
src/shared/reducers/challenge-listing/index.js

Reverts topcoder-platform/community-app#1952

Revert "listing perfomance fix"

---

src/shared/actions/challenge-listing/index.js
src/shared/reducers/challenge-listing/index.js

Reverts topcoder-platform/community-app#1955

Revert "restore renamed actions for loading all challenges"

---

src/shared/utils/memberStats.js

Reverts topcoder-platform/community-app#1954

Revert "Add rating details in Code track"

---

src/shared/actions/challenge-listing/index.js
src/shared/reducers/challenge-listing/index.js

Reverts topcoder-platform/community-app#1961

Revert "Revert "restore renamed actions for loading all challenges""

---

__tests__/shared/components/Settings/Profile/AboutMe/__snapshots__/index.jsx.snap
src/shared/components/Settings/Profile/AboutMe/index.jsx
src/shared/components/Settings/Profile/BasicInfo/ImageInput/index.jsx

The delete avatar functionality is not supported by the backend and the button was useless.
fixes #1307

Remove delete avatar button as there is no delete functionality on the backend

---

src/assets/images/review-opportunity-load-error.svg
src/shared/components/ReviewOpportunityDetailsPage/FailedToLoad/index.jsx
src/shared/components/ReviewOpportunityDetailsPage/FailedToLoad/styles.scss

Reverts topcoder-platform/community-app#1960

Revert "Revert "Fixes #1284" by Thomas"

---

src/server/index.js

Reverts topcoder-platform/community-app#1973

Revert "Update index.js"

---

src/shared/components/Settings/Account/MyAccount/index.jsx

@sushilshinde it would be great if you can push this to prod

Fix URLs for the email verification link

---

.circleci/config.yml

Reverts topcoder-platform/community-app#2010 [skip ci]

Revert "pushing masterscript for master branch" [skip ci]

---

.circleci/config.yml

Update config.yml [skip ci]

---

.circleci/config.yml

Reverts topcoder-platform/community-app#2022

Revert "Masterscript v1.3 update - space issue"

---

.circleci/config.yml
build.sh

Develop masterscript [skip ci]

---

src/shared/components/challenge-detail/Specification/styles.scss

Issue on challenge details page | CSS fix #1993

Issue on challenge details page | CSS fix #1993

---

src/shared/components/ProfilePage/BadgesModal/achievementMap.js

issues_2150 Badges are not shown for some members

---

src/shared/components/Settings/Profile/BasicInfo/ImageInput/index.jsx
src/shared/components/Settings/Profile/BasicInfo/ImageInput/styles.scss

If the user upload image more than 2MB, an error message will be shown

Ticket #2161 - Fix user can upload oversize image to avatar

---

src/shared/components/Settings/CofirmationModal/index.jsx
src/shared/components/Settings/CofirmationModal/styles.scss
src/shared/components/Settings/Profile/Hobby/index.jsx
src/shared/components/Settings/Tools/Devices/index.jsx
src/shared/components/Settings/Tools/ServiceProviders/index.jsx
src/shared/components/Settings/Tools/Software/index.jsx
src/shared/components/Settings/Tools/Subscriptions/index.jsx

show confirmation on delete

---

src/shared/components/Settings/Account/LinkedAccount/AddWebLink.jsx

Fix error while adding valid external link

---

src/shared/components/Settings/Account/LinkedAccount/modal.scss
src/shared/components/Settings/CofirmationModal/styles.scss

Modal not fitting properly on phone

---

src/shared/components/Settings/Profile/BasicInfo/index.jsx

…er settings
In addition to "description field", all fields in address + primary interest field + currentLocation field are trimmed as well

Ticket #2168- Trim optional fields in user profile settings

---

src/shared/components/ChallengeTile/index.jsx

Fix issue by protecting submissionReviewScore

Protect submissionReviewScore

---

src/shared/utils/memberStats.js

Showing Country Rank `-` if servers returns 0

Fix for issues-2179

---

src/shared/components/Settings/Profile/BasicInfo/index.jsx

Fix keyboard

---

__tests__/shared/components/Settings/__snapshots__/index.jsx.snap
src/shared/components/Settings/index.jsx

Fix datepicker not hiding on ipad

---

.eslintrc
src/shared/components/Settings/Account/index.jsx
src/shared/components/Settings/Profile/index.jsx
src/shared/components/Settings/Tools/index.jsx

Deep link profile

---

src/shared/components/Settings/Preferences/Email/index.jsx
src/shared/containers/Settings.jsx

Fix toggle buttons in preferences

---

src/shared/components/Settings/Profile/BasicInfo/index.jsx
src/shared/components/Settings/Profile/Hobby/index.jsx
src/shared/components/Settings/Profile/Skills/index.jsx
src/shared/components/Settings/Tools/Devices/index.jsx
src/shared/components/Settings/Tools/ServiceProviders/index.jsx
src/shared/components/Settings/Tools/Software/index.jsx
src/shared/components/Settings/Tools/Subscriptions/index.jsx

Disable form while saving

---

__tests__/shared/components/Settings/Account/__snapshots__/index.jsx.snap
__tests__/shared/components/Settings/Preferences/__snapshots__/index.jsx.snap
src/shared/components/Settings/Account/index.jsx
src/shared/components/Settings/Preferences/index.jsx
src/shared/components/Settings/Profile/index.jsx
src/shared/components/Settings/Tools/Devices/index.jsx
src/shared/components/Settings/Tools/ServiceProviders/index.jsx
src/shared/components/Settings/Tools/Software/index.jsx
src/shared/components/Settings/Tools/Subscriptions/index.jsx
src/shared/components/Settings/Tools/index.jsx
src/shared/components/Settings/constants.js

The scope covered more than the ticket scope.
1. fixes notification not showing up correctly in settings tab, and dismiss notification when switch tabs
2. improve code style, moving constants out of this.state(which should only contain values that trigger re-render), and optimize tabs change using componentDidUpdate.
3. detect mobile view and only render either of desktop or mobile view in tabs, compared to we show both of them in current implementation. and triggers multiple duplicate actions.
4. revert pr https://github.com/topcoder-platform/community-app/pull/2257 for https://github.com/topcoder-platform/community-app/issues/2163 as it didn't solve the real problem

#2096 Fix settings notifications not showing when update user traits

---

src/shared/components/Settings/Profile/Skills/index.jsx

Fix for issues#2052

---

src/shared/components/ProfilePage/index.jsx
src/shared/containers/Dashboard/index.jsx
src/shared/containers/Profile.jsx

@ThomasKranitsas please check it

Remove V2 API from Dashboard and Profile Page

---

src/shared/components/ProfilePage/index.jsx

Fix for issues-2341

---

src/shared/components/challenge-listing/Listing/Bucket/index.jsx

code 30090056

---

src/shared/components/Settings/Preferences/Email/index.jsx

Raising against the challenge https://www.topcoder.com/challenges/30090204/?type=develop&tab=details

update email preferences to use v5 api

---

src/shared/components/Contentful/Menu/index.jsx
src/shared/containers/ChallengesBlock.jsx
src/shared/containers/Dashboard/index.jsx
src/shared/containers/tc-communities/CommunityStats.jsx
src/shared/containers/tc-communities/Loader.jsx
src/shared/containers/tc-communities/cognitive/home.jsx
src/shared/utils/contentful.js

@ThomasKranitsas Please check it

Fixed issues of server-side filtering on challenge listings

---

src/shared/containers/challenge-listing/FilterPanel.jsx

Challenge Listing Page: Sub community dropdown has only one value #2381

Challenge Listing Page: Sub community dropdown has only one value #2381

---

src/shared/containers/challenge-listing/Listing/index.jsx

Reverts topcoder-platform/community-app#2409

Revert "Fix for Issue #2391"

---

__tests__/shared/components/Header/__snapshots__/index.jsx.snap
config/default.js
config/production.js

#2453   
Fix the community links in header menu configuration from hardcoded fixed value to be based on current domain in use.

Fix for issue #2453

---

__tests__/shared/components/Header/__snapshots__/index.jsx.snap
config/default.js
config/production.js

Fix for issues#2395

---

src/shared/components/ProfilePage/ExternalLink/index.jsx

Fix Profile Page loading issue

Fix for Profile Page loading issue

---

__tests__/shared/containers/__snapshots__/TopcoderHeader.jsx.snap
src/shared/containers/TopcoderHeader.js

#2639 
Add roles to the profile in header to enable checking in navigation component.

Fix for issue #2639

---

__tests__/shared/components/Header/__snapshots__/index.jsx.snap
config/default.js
config/production.js
src/shared/components/Header/index.jsx

Fix Issue 2396 - v2

---

src/shared/components/challenge-listing/Listing/Bucket/index.jsx
src/shared/components/challenge-listing/Listing/index.jsx
src/shared/components/challenge-listing/index.jsx
src/shared/containers/challenge-listing/Listing/index.jsx

Fix my challenges bucket

---

.circleci/config.yml
src/shared/components/Settings/Profile/Skills/index.jsx
src/shared/components/Settings/Profile/Skills/styles.scss

Fix for issue #2642

---

src/shared/components/challenge-listing/Listing/Bucket/index.jsx

fix view more challenge button

---

src/shared/containers/challenge-listing/Listing/index.jsx

Fix for Issue #2695

---

src/shared/components/challenge-listing/Sidebar/BucketSelector/Bucket/index.jsx

Hide "My Challenges" when user is not logged in

issue#2693: Hide "My Challenges" when user is not logged in

---

src/shared/components/ProfilePage/Header/styles.scss

Reverts topcoder-platform/community-app#2951

Revert "Issue 2885 fix"

---

src/shared/components/TopcoderHeader/Auth/style.scss

Reverts topcoder-platform/community-app#2953

Revert "issue 2907 done"

---

.circleci/config.yml
package-lock.json
package.json
src/shared/components/challenge-detail/Submissions/SubmissionRow/SubmissionHistoryRow/index.jsx
src/shared/components/challenge-detail/Submissions/SubmissionRow/index.jsx
src/shared/components/challenge-detail/Submissions/index.jsx
src/shared/containers/challenge-detail/index.jsx

Reverts topcoder-platform/community-app#2961

Revert "Mm updated leaderboard with fixes"

---

__tests__/shared/__snapshots__/index.jsx.snap
src/shared/app.jsx

#2739 
MSFT-15 Add lang attribute.

Fix for Issue #2739 - Add lang attribute

---

src/shared/components/challenge-listing/ChallengeCard/style.scss

#2887 
MSFT-229 Do not read-out when user point to empty locations.

Fix for Issue #2887 MSFT-229

---

src/assets/images/tco19_logo_black.svg

Fix for Issue #2819 - Eligible event

---

__tests__/shared/components/TopcoderHeader/__snapshots__/Auth.jsx.snap
src/shared/components/TopcoderHeader/Auth/index.jsx

MSFT-236-Issue#2893 - proper name read out when hover on join or login button

---

__tests__/shared/components/__snapshots__/TopcoderFooter.jsx.snap
src/shared/components/TopcoderFooter/index.jsx

MSFT-200 #2865

---

src/shared/components/challenge-listing/Listing/Bucket/style.scss

MSFT 178 issue#2850 - added border on view more challenges button focus state

---

src/shared/components/challenge-listing/Sidebar/BucketSelector/Bucket/style.scss

MSFT-17 & MSFT-35

---

__tests__/shared/components/TopcoderHeader/desktop/SubMenu/Item.jsx
__tests__/shared/components/TopcoderHeader/desktop/SubMenu/__snapshots__/Item.jsx.snap
src/shared/components/TopcoderHeader/desktop/SubMenu/Item/index.jsx

#2836 
Read sub-menu link when hovered.

Fix for Issue #2836 - Read submenu link on hover

---

src/assets/images/logo_topcoder.svg
src/shared/components/TopcoderHeader/mobile/Header/index.jsx

changes for https://github.com/topcoder-platform/community-app/issues/2740

MSFT-16 Mobile Fix

---

src/shared/components/SubmissionPage/Submit/styles.scss

changes for #2844

---

src/shared/components/SubmissionPage/Header/styles.scss

changes for #2842

---

src/shared/components/SubmissionPage/FilestackFilePicker/index.jsx

changes for #2841

---

src/shared/components/challenge-detail/Specification/SideBar/index.jsx

MSFT-233 Issue#2891

---

src/shared/components/SubmissionPage/FilestackFilePicker/index.jsx

https://github.com/topcoder-platform/community-app/issues/2902

Change improper role attr of drag drop submission form.

---

src/shared/components/challenge-detail/Header/DeadlinesPanel/index.jsx

#2832 
MSFT-136 Read out the deadline section on challenge detail page.

Fix for Issue #2832 Deadlines section

---

src/client/index.jsx

community app issue-2853

---

src/shared/components/SubmissionPage/Submit/styles.scss

This PR is dependent on https://github.com/topcoder-platform/topcoder-react-ui-kit/pull/11 for color

fix for #2846

---

src/shared/containers/SubmissionPage.jsx

changes for #2799

---

src/client/styles.scss

Fix #2911 [MSFT-264] Keyboard access tab operational missing

---

src/shared/components/Contentful/ContentBlock/themes/general.scss

Changes for https://github.com/topcoder-platform/community-app/issues/3136

Issue 3136 fix

---

src/shared/components/SortingSelectBar/style.scss

Issue 2874 fix

---

__tests__/shared/components/TopcoderHeader/__snapshots__/index.jsx.snap
src/shared/components/TopcoderHeader/index.jsx
src/shared/components/TopcoderHeader/style.scss

Changes for https://github.com/topcoder-platform/community-app/issues/3092

Issue 3092 fix

---

src/shared/components/Contentful/Viewport/Viewport.jsx

Changes for https://github.com/topcoder-platform/community-app/issues/3089

Issue 3089 fix

---

src/shared/components/Contentful/Banner/themes/general.scss
src/shared/components/Contentful/ContentBlock/themes/general.scss

Issue 3096 fix

---

src/shared/components/challenge-detail/Specification/SideBar/EligibleEvents/index.jsx

Fixes https://github.com/topcoder-platform/community-app/issues/2820

MSFT-122-Issue#2820 - fixed heading level

---

src/shared/components/TrackIcon/style.scss

Changes for https://github.com/topcoder-platform/community-app/issues/2745

MSFT-22 New

---

__tests__/shared/components/TopcoderHeader/__snapshots__/Auth.jsx.snap
src/shared/components/TopcoderHeader/Auth/index.jsx

Changes for https://github.com/topcoder-platform/community-app/issues/3085

Fix login button for screen reader

---

__tests__/shared/components/TopcoderHeader/__snapshots__/Auth.jsx.snap
src/shared/components/TopcoderHeader/Auth/index.jsx

Fixes https://github.com/topcoder-platform/community-app/issues/2893

MSFT 236 issue#2893

---

src/shared/components/SubmissionPage/Header/index.jsx
src/shared/components/SubmissionPage/Header/styles.scss

changes for fail test and fix
Issue #2799

changes for 2799

---

src/shared/components/challenge-listing/ChallengeCard/Prize/index.jsx

MSFT-102 | Minor fix

---

src/shared/components/SubmissionPage/Submit/index.jsx
src/shared/components/SubmissionPage/Submit/styles.scss

changes for #3185

---

__tests__/shared/components/TopcoderHeader/__snapshots__/index.jsx.snap
src/shared/components/TopcoderHeader/index.jsx

#2817 
Fix the Topcoder Logo to be read out as "Topcoder Logo link to Topcoder Homepage"

Fix the reading of Topcoder Logo

---

src/shared/components/challenge-detail/Specification/SideBar/index.jsx

Changes for https://github.com/topcoder-platform/community-app/issues/2797

MSFT-86 | Update tooltip for review scorecard

---

src/shared/components/challenge-detail/Header/Prizes.jsx

Changes for https://github.com/topcoder-platform/community-app/issues/2828

MSFT-131 | Fix double reading

---

src/shared/components/SubmissionPage/FilestackFilePicker/index.jsx

Changes for https://github.com/topcoder-platform/community-app/issues/2807

MSFT-103 | Minor Fixes

---

__tests__/shared/components/ProfilePage/__snapshots__/index.jsx.snap
src/shared/components/ProfilePage/Stats/StatsModal/index.jsx
src/shared/components/ProfilePage/Stats/index.jsx
src/shared/components/ProfilePage/StatsCategory/index.jsx
src/shared/components/ProfilePage/index.jsx
src/shared/components/tc-communities/Header/index.jsx
src/shared/containers/Dashboard/index.jsx
src/shared/containers/Profile.jsx
src/shared/containers/ProfileStats.jsx
src/shared/containers/tc-communities/Loader.jsx
src/shared/routes/Communities/Blockchain/Routes.jsx
src/shared/routes/Communities/Profile.jsx
src/shared/routes/Communities/ProfileStats.jsx
src/shared/routes/Communities/Veterans/Routes.jsx
src/shared/routes/Communities/Wipro/Routes.jsx

Challenge: 30099138

---

__tests__/shared/components/__snapshots__/SortingSelectBar.jsx.snap
src/shared/components/SortingSelectBar/index.jsx
src/shared/components/challenge-listing/ChallengeCard/index.jsx

Changes for https://github.com/topcoder-platform/community-app/issues/3245

Change heading | Issue #3245

---

src/shared/components/TrackIcon/style.scss
src/shared/components/challenge-detail/Specification/SideBar/styles.scss
src/shared/components/examples/ColorMixins/Color/style.scss
src/shared/components/examples/ColorMixins/index.jsx

Changes for topcoder-platform/community-app#3060

Issue 3060 | Update colors

---

__tests__/shared/components/TopcoderHeader/__snapshots__/index.jsx.snap
src/shared/components/TopcoderHeader/index.jsx

Reverts topcoder-platform/community-app#3261
based on feedback https://github.com/topcoder-platform/community-app/issues/3246#issuecomment-525288589

Revert "Issue 3246 fix"

---

__tests__/shared/components/challenge-listing/Filters/__snapshots__/ChallengeFilters.jsx.snap
__tests__/shared/components/challenge-listing/Filters/__snapshots__/ChallengeSearchBar.jsx.snap
src/shared/components/challenge-listing/Filters/ChallengeFilters.jsx
src/shared/components/challenge-listing/Filters/ChallengeSearchBar/index.jsx
src/shared/components/challenge-listing/Filters/ChallengeSearchBar/style.scss

Changes for https://github.com/topcoder-platform/community-app/issues/3242

Issue 3242 | Add label for Search Challenges Input

---

src/shared/components/TopcoderHeader/mobile/Header/index.jsx

Changes for https://github.com/topcoder-platform/community-app/issues/3234

Issue 3234 | Remove duplicate banner landmark

---

__tests__/shared/components/challenge-listing/Filters/FiltersCardsType.jsx
__tests__/shared/components/challenge-listing/Filters/__snapshots__/FiltersCardsType.jsx.snap
src/shared/components/challenge-listing/Filters/FiltersCardsType/index.jsx
src/shared/components/challenge-listing/Filters/FiltersCardsType/style.scss

Changes for https://github.com/topcoder-platform/community-app/issues/3245

Issue #3245 | Add H1 heading

---

src/shared/components/TrackIcon/style.scss

Changes for https://github.com/topcoder-platform/community-app/issues/3060

Issue #3060 | Update colors

---

.circleci/config.yml
src/shared/components/tc-communities/Footer2/index.jsx
src/shared/components/tc-communities/communities/veterans/Footer/index.jsx
src/shared/components/tc-communities/communities/wipro/Footer/index.jsx
src/shared/components/tc-communities/communities/wipro/Home/index.jsx
src/shared/containers/challenge-listing/Listing/index.jsx
src/shared/routes/Communities/Zurich/Routes.jsx

Reverts topcoder-platform/community-app#3358

Revert "Merge hot-fix to develop"

---

src/shared/components/challenge-detail/Registrants/style.scss

fix background for header registants in safari

fix background for header registrants  in safari

---

.circleci/config.yml
src/shared/containers/challenge-listing/Listing/index.jsx

Push a quick survey to challenges page

---

.circleci/config.yml
src/shared/containers/challenge-listing/Listing/index.jsx

Push a quick survey to challenges page for master

---

.circleci/config.yml
config/jest/default.js
config/webpack/default.js
docs/deployment-env.md
package-lock.json
package.json

Reverts topcoder-platform/community-app#3367

Revert "Build improvement"

---

__tests__/shared/components/Header/__snapshots__/index.jsx.snap
config/default.js
config/production.js

Fix issue #3444 : Always show sub nav when page have your own menu.

---

.circleci/config.yml
config/default.js
src/server/index.js
src/server/services/contentful.js

TC blog to Thrive bridge

---

src/shared/actions/page/challenge-details.js
src/shared/components/challenge-detail/Header/TabSelector/index.jsx
src/shared/components/challenge-detail/Header/index.jsx
src/shared/components/challenge-detail/MySubmissions/SubmissionsDetail/index.jsx
src/shared/components/challenge-detail/MySubmissions/SubmissionsDetail/styles.scss
src/shared/components/challenge-detail/MySubmissions/SubmissionsList/index.jsx
src/shared/components/challenge-detail/MySubmissions/SubmissionsList/styles.scss
src/shared/components/challenge-detail/MySubmissions/index.jsx
src/shared/components/challenge-detail/MySubmissions/styles.scss
src/shared/components/challenge-detail/Submissions/index.jsx
src/shared/components/challenge-detail/Submissions/style.scss
src/shared/components/challenge-detail/icons/queued.svg
src/shared/containers/challenge-detail/index.jsx

Code 30108491

---

.circleci/config.yml
__tests__/shared/utils/__snapshots__/markdown.js.snap
package-lock.json
package.json
src/server/index.js
src/shared/components/Contentful/Article/themes/default.scss
src/shared/components/Looker/index.jsx
src/shared/containers/tc-communities/Loader.jsx
src/shared/utils/markdown.js

Contentful development

---

.circleci/config.yml
src/shared/components/ProfilePage/Stats/index.jsx
src/shared/components/ProfilePage/Stats/styles.scss

Issue #3465

---

__tests__/shared/components/Header/__snapshots__/index.jsx.snap
config/default.js
config/production.js

https://github.com/topcoder-platform/navigation-component/issues/58

Fix TCO link

---

__tests__/shared/components/Header/__snapshots__/index.jsx.snap
config/default.js
config/production.js

Issues 3519

---

src/assets/images/tc-logo.svg

issue-2559-iversonLv Hover on Logo is displaying inappropriate details.

---

.circleci/config.yml
src/shared/components/Leaderboard/Podium/index.jsx
src/shared/components/Leaderboard/PodiumSpot/index.jsx
src/shared/components/Leaderboard/PodiumSpot/themes/tco20.scss
src/shared/components/Leaderboard/avatarStyles.scss
src/shared/containers/tco/Leaderboard/index.jsx
src/shared/containers/tco/Leaderboard/themes/styles.scss

Implements #3552

---

config/default.js
config/production.js

https://github.com/topcoder-platform/navigation-component/issues/104  
Add new HOME url value in configuration to link the logo when logged in.

Fix Navigation Component Issue #104 Add new HOME URL config value

---

src/shared/containers/challenge-listing/Listing/index.jsx

#3548   
No loading active challenges when pulling up past challenges to increase performance

Fix for Issue #3548 Pulling up Past Challenges

---

.circleci/config.yml

hot fix for the ticket after QA Pass:
https://github.com/topcoder-platform/community-app/issues/3548

Hot fix performance

---

.circleci/config.yml

https://github.com/topcoder-platform/community-app/issues/3536
This ticket is ready for smoke test.

Hot fix challenge details

---

src/shared/utils/challenge-listing/buckets.js

fix text issue

---

.circleci/config.yml
.github/workflows/commitlint.yml

Contain the fix for this ticket: https://github.com/topcoder-platform/community-app/issues/3978

Hot fixes leaderboard

---

src/shared/components/tc-communities/Header/index.jsx

Reverts topcoder-platform/community-app#4062

Revert "fix profile redirection"

---

package.json

https://github.com/topcoder-platform/community-app/issues/3474

Hot fix skills tag 2

---

.circleci/config.yml
config/webpack/default.js

PR contain fixes for https://github.com/topcoder-platform/community-app/issues/4118

Hot fix image issue

---

.circleci/config.yml
package.json
src/shared/components/Settings/Profile/BasicInfo/ImageInput/styles.scss
src/shared/components/Settings/Profile/Education/styles.scss
src/shared/components/Settings/Profile/Work/styles.scss
src/shared/components/Settings/Tools/Subscriptions/styles.scss
src/shared/components/tc-communities/Header/index.jsx
src/shared/components/tc-communities/communities/wipro/theme/buttons/default.scss
src/shared/routes/Communities/Blockchain/Routes.jsx
src/shared/routes/Communities/CS/Routes.jsx
src/shared/routes/Communities/Cognitive/Routes.jsx
src/shared/routes/Communities/Veterans/Routes.jsx
src/shared/routes/Communities/Wipro/Routes.jsx

The PR contains code for this ticket: 
https://github.com/topcoder-platform/community-app/issues/4088

Feature private setting

---

.circleci/config.yml
src/shared/components/ProfilePage/StatsCategory/index.jsx
src/shared/components/ProfilePage/index.jsx

This PR includes the fix for this ticket:
https://github.com/topcoder-platform/community-app/issues/4134

Hot fix profile page

---

src/server/tc-communities/comcast/metadata.json

Remove TC logo from Comcast

---

src/shared/components/ProfilePage/Header/index.jsx
src/shared/components/ProfilePage/Header/styles.scss
src/shared/components/ProfilePage/index.jsx

Fix show best rating color in profile.

Fix show best rating color in profile.

---

src/shared/components/challenge-listing/Filters/ChallengeSearchBar/style.scss

Fix a bug due to which the 'x' button overlapped with the text.

Fix a bug due to which the 'x' button overlapped with the text.

---

src/shared/components/ProfilePage/StatsCategory/index.jsx
src/shared/utils/memberStats.js

Fix issue 4293, remove Development Activity's incorrect sections.

Fix issue 4293, remove Development Activity's incorrect sections.

---

.circleci/config.yml
package.json

https://github.com/topcoder-platform/community-app/issues/4312

hot-fix for hall-of-fame

---

.circleci/config.yml
config/default.js

https://github.com/topcoder-platform/community-app/issues/4418

ci: disable SW and deploy on beta env

---

package-lock.json
src/shared/components/SubmissionPage/Submit/index.jsx
src/shared/components/challenge-detail/Submissions/index.jsx
src/shared/components/challenge-listing/ChallengeCard/index.jsx
src/shared/components/challenge-listing/Tooltips/ProgressBarTooltip/index.jsx

https://github.com/topcoder-platform/community-app/issues/4377

Changes phase.isActive to phase.isOpen

---

config/default.js
src/shared/actions/challenge-listing/index.js
src/shared/components/Dashboard/CurrentActivity/Challenges/ChallengeCard/index.jsx
src/shared/containers/Dashboard/index.jsx

issue: https://github.com/topcoder-platform/community-app/issues/4378
dependency: https://github.com/topcoder-platform/topcoder-react-lib/pull/169

Issue 4378

---

src/shared/actions/challenge-listing/index.js
src/shared/components/challenge-listing/Listing/index.jsx
src/shared/containers/challenge-listing/Sidebar.jsx
src/shared/utils/challenge-listing/buckets.js

fix for Issue #4384

---

src/server/index.js
src/shared/containers/SubmissionManagement/index.jsx
src/shared/containers/SubmissionPage.jsx
src/shared/containers/challenge-detail/index.jsx

Issue: #4380
Dependency: https://github.com/topcoder-platform/topcoder-react-lib/pull/190

Issue#4380 - Removed proxyApi and change isRegistered function

---

src/assets/images/arrow-down.svg
src/shared/components/challenge-detail/Registrants/index.jsx
src/shared/components/challenge-detail/Submissions/index.jsx
src/shared/containers/challenge-detail/index.jsx

Issue: https://github.com/topcoder-platform/community-app/issues/4536
Dependency: https://github.com/topcoder-platform/topcoder-react-lib/pull/197

Issue #4536 - Fix Challenge Details submissions tab

---

src/shared/utils/challenge-detail/helper.jsx

Registration: Loading a blank page when trying to register to Marathon Match contest

Issue 4549

---

src/shared/components/challenge-detail/Header/TabSelector/index.jsx
src/shared/components/challenge-detail/Header/index.jsx
src/shared/containers/challenge-detail/index.jsx

Issue: https://github.com/topcoder-platform/community-app/issues/4536#issuecomment-645350455

Issue#4536 : Hide Submission tab if user not logged

---

src/shared/components/SubmissionManagement/SubmissionManagement/index.jsx
src/shared/components/SubmissionPage/Submit/index.jsx
src/shared/components/SubmissionPage/index.jsx
src/shared/components/challenge-detail/Header/index.jsx
src/shared/components/challenge-detail/MySubmissions/SubmissionsList/index.jsx
src/shared/components/challenge-detail/MySubmissions/index.jsx
src/shared/components/challenge-detail/RecommendedActiveChallenges/ChallengesCard/index.jsx
src/shared/components/challenge-detail/Registrants/index.jsx
src/shared/components/challenge-detail/Submissions/index.jsx
src/shared/components/challenge-listing/ChallengeCard/Status/index.jsx
src/shared/components/challenge-listing/ChallengeCard/index.jsx
src/shared/components/challenge-listing/Tooltips/ProgressBarTooltip/index.jsx
src/shared/containers/SubmissionManagement/index.jsx
src/shared/containers/SubmissionPage.jsx
src/shared/containers/challenge-detail/index.jsx

Issue#4498 : Fix challenge submissions page

---

src/server/sw.js
src/shared/containers/SubmissionPage.jsx
src/shared/reducers/index.js
src/shared/reducers/reviewOpportunity.js
src/shared/reducers/terms.js
src/shared/routes/Communities/Blockchain/Routes.jsx
src/shared/routes/Communities/CS/Routes.jsx
src/shared/routes/Communities/Cognitive/Routes.jsx
src/shared/routes/Communities/Comcast/Routes.jsx
src/shared/routes/Communities/Community2/Routes.jsx
src/shared/routes/Communities/DemoExpert/Routes.jsx
src/shared/routes/Communities/Mobile/Routes.jsx
src/shared/routes/Communities/QA/Routes.jsx
src/shared/routes/Communities/SRMx/Routes.jsx
src/shared/routes/Communities/TaskForce/Routes.jsx
src/shared/routes/Communities/TcProdDev/Routes/index.jsx
src/shared/routes/Communities/Veterans/Routes.jsx
src/shared/routes/Communities/Wipro/Routes.jsx
src/shared/routes/Communities/Zurich/Routes.jsx
src/shared/routes/Communities/iot/Routes.jsx
src/shared/routes/Topcoder/Routes.jsx
src/shared/routes/tco/scoreboard/index.jsx

Issue: https://github.com/topcoder-platform/community-app/issues/4565

Issue #4565 - Fix UUID validation and props in Submission page

---

src/shared/actions/terms.js

Issue: https://github.com/topcoder-platform/community-app/issues/4562
Dependecy: https://github.com/topcoder-platform/topcoder-react-lib/pull/204

Issue#4562 : Fix getTermsDone return

---

__tests__/shared/components/Header/__snapshots__/index.jsx.snap
config/default.js
config/production.js

#4297 : Add "Practice" to drop down navigation

---

src/shared/components/challenge-detail/Header/index.jsx

Issue: https://github.com/topcoder-platform/community-app/issues/4590

Issue#4590 : Fix hasSubmissions in Challenge Details page

---

src/shared/components/Terms/index.jsx

Added `viewing_complete` to DocuSign message return

---

package-lock.json
src/shared/components/challenge-detail/Specification/SideBar/index.jsx
src/shared/components/challenge-detail/Specification/SideBar/styles.scss
src/shared/components/challenge-detail/Specification/index.jsx

Add legacy challenge id at the bottom right corner of the
challenge-detail/Specification/SideBar component.
Addresses topcoder-platform/community-app#4658

feat(challenge-detail): add legacy challenge id

---

src/shared/utils/challenge-listing/buckets.js

Issue: https://github.com/topcoder-platform/community-app/issues/4688
Dependency: https://github.com/topcoder-platform/topcoder-react-lib/pull/213

issue#4688 : Added ongoing filter to challenges listing

---

__tests__/shared/components/Contentful/Image/__snapshots__/Image.jsx.snap
__tests__/shared/components/Contentful/MemberCard/__snapshots__/MemberCard.jsx.snap
src/shared/components/Contentful/Tabs/Tabs.jsx
src/shared/components/Contentful/Tabs/themes/underline-dark.scss
src/shared/utils/contentful.js

Feature contentful

---

src/shared/components/Dashboard/CurrentActivity/Challenges/ChallengeCard/index.jsx
src/shared/components/challenge-detail/RecommendedActiveChallenges/ChallengesCard/index.jsx
src/shared/components/challenge-listing/ChallengeCard/index.jsx

fix for TCO flag display

---

__tests__/shared/components/challenge-listing/Tooltips/__snapshots__/TrackAbbreviationTooltip.jsx.snap
src/shared/components/challenge-listing/Tooltips/TrackAbbreviationTooltip/index.jsx
src/shared/components/challenge-listing/Tooltips/TrackAbbreviationTooltip/style.scss

Issue: https://github.com/topcoder-platform/community-app/issues/4720

Fix tooltip in challenge listing page

---

src/shared/utils/challenge.js

Issue: https://github.com/topcoder-platform/community-app/issues/4709

Hotfix - isMM()

---

src/shared/utils/challenge-listing/sort.js

Fix for MOST_RECENT, TIME_TO_REGISTER and TIME_TO_SUBMIT sortings.
* Since the V5 API  returns inconistent values for
(`registrationStartDate`, `registrationEndDate`, `submissionStartDate`, `submissionEndDate`),
these dates will now be extracted from `challenge.phases` array.
Reference topcoder-platform/community-app#4715, topcoder-platform/community-app#4716

fix(challenge-listing): sorting functions

---

src/shared/containers/SubmissionPage.jsx

Issue: https://github.com/topcoder-platform/community-app/issues/4632

Redirect /challenge/legacyId/submit to /challenge/UUID/submit

---

src/shared/utils/challenge-listing/sort.js

Addresses topcoder-platform/community-app#4129

fix(challenge-listing): `CURRENT_PHASE` sorting

---

src/shared/components/challenge-detail/Submissions/index.jsx
src/shared/containers/challenge-detail/index.jsx

Issue: https://github.com/topcoder-platform/community-app/issues/4667

Challenge Details - Fix submissions memberHandle

---

src/shared/actions/tc-communities/index.js

Issue: https://github.com/topcoder-platform/community-app/issues/4806

Fix sub-communities filter does not include private communities

---

src/shared/components/challenge-listing/Listing/ReviewOpportunityBucket/index.jsx

Issue: https://github.com/topcoder-platform/community-app/issues/4739

ReviewOpportunityCard - Fix console warning about propType

---

src/server/tc-communities/tco20/metadata.json
src/server/tc-communities/tco21/metadata.json
src/shared/containers/challenge-listing/Listing/index.jsx

Issue: https://github.com/topcoder-platform/community-app/issues/4575
Dependency: https://github.com/topcoder-platform/topcoder-react-lib/pull/231

Issue#4575 - Sub community filter not working

---

src/server/tc-communities/tco19/metadata.json

Issue: https://github.com/topcoder-platform/community-app/issues/4575
Dependency: https://github.com/topcoder-platform/topcoder-react-lib/pull/231

Challenge Listing - Fix TCO19 filter

---

src/shared/components/challenge-detail/MySubmissions/index.jsx
src/shared/components/challenge-detail/Submissions/index.jsx
src/shared/containers/challenge-detail/index.jsx

Issue: https://github.com/topcoder-platform/community-app/issues/4730
Dependency: https://github.com/topcoder-platform/topcoder-react-lib/pull/235

Issue#4730 : Fix MM submissions

---

__tests__/shared/components/challenge-listing/__snapshots__/index.jsx.snap
src/shared/actions/challenge-listing/index.js
src/shared/components/challenge-listing/Listing/index.jsx
src/shared/components/challenge-listing/index.jsx
src/shared/containers/challenge-listing/Listing/index.jsx
src/shared/containers/challenge-listing/Sidebar.jsx
src/shared/utils/challenge-listing/buckets.js
src/shared/utils/challenge-listing/helper.js

fix: my challenges bucket

---

src/shared/components/challenge-detail/Header/DeadlinesPanel/index.jsx
src/shared/components/challenge-detail/Header/index.jsx
src/shared/utils/challenge-listing/helper.js

fix(challenge-detail): wrong dates/phases at deadlines panel

---

src/shared/components/SubmissionManagement/SubmissionManagement/index.jsx

Add null checking when rendering properties from `currentPhase`
Reference #4758

fix(submission-management): add null checking for `currentPhase`

---

src/shared/components/SubmissionPage/Submit/index.jsx

Issue: https://github.com/topcoder-platform/community-app/issues/4844

Fix Topgear submissions page

---

.circleci/config.yml
package.json
src/shared/components/ProfilePage/Stats/HistoryGraph/index.jsx
src/shared/components/SubmissionPage/Submit/index.jsx

Milestone-20200910

---

src/shared/components/challenge-listing/Sidebar/BucketSelector/index.jsx

Hide RSS feature from front-end

---

__tests__/shared/components/Header/__snapshots__/index.jsx.snap
config/default.js
config/production.js

Fix for #4347 - Open blog page in new, separate tab

---

src/shared/routes/index.jsx

Issue: https://github.com/topcoder-platform/community-app/issues/4895

issue 4895 fix

---

__tests__/shared/components/ChallengeTile/__snapshots__/index.jsx.snap
src/shared/components/ChallengeTile/index.jsx

ChallengeTile: Fix MM link to Challenge details page

---

__tests__/shared/components/SubmissionManagement/__snapshots__/Submission.jsx.snap
src/shared/components/SubmissionManagement/Submission/index.jsx
src/shared/components/SubmissionManagement/Submission/styles.scss

Issue: https://github.com/topcoder-platform/community-app/issues/4858

f2f submissionidlegacyid

---

src/shared/components/SubmissionManagement/Submission/index.jsx

F2f submissionlegacyid

---

src/shared/components/ProfilePage/Header/index.jsx

fix(profile-page): add spacing before wins count

---

config/default.js
src/client/index.jsx

Remove reauth from community-app

---

src/client/index.jsx

Re added refresh token to community-app

---

src/shared/components/challenge-listing/Filters/ChallengeFilters.jsx

#4966 Display the number of filters applied

Fix for Issue #4966

---

src/shared/components/challenge-listing/Listing/index.jsx
src/shared/reducers/challenge-listing/index.js
src/shared/utils/url.js

This PR fixes: 
https://github.com/topcoder-platform/community-app/issues/4963
https://github.com/topcoder-platform/community-app/issues/4972

Feature refactor challengelist fixes

---

package.json
src/shared/components/SubmissionManagement/Submission/index.jsx
src/shared/utils/tc.js

Issue: #4948 
Dependency: https://github.com/topcoder-platform/topcoder-react-lib/pull/262

SubmissionManagement - Hide DELETE button from Design track

---

src/shared/components/Dashboard/CurrentActivity/Header/index.jsx
src/shared/reducers/page/dashboard.js

Temporary hide MY ACTIVE CHALLENGES in Dashboard

---

src/shared/components/ChallengeTile/index.jsx

Issue 4926 fix

---

.circleci/config.yml
src/shared/containers/GigsPages.jsx

Gig pages chatbot

---

__tests__/client/client.jsx
__tests__/shared/reducers/auth.js
__tests__/shared/reducers/challenge.js
bin/www
config/jest/default.js
config/webpack/development.js
config/webpack/production.js
package.json
src/client/index.jsx
src/shared/actions/challenge-listing/index.js
src/shared/components/challenge-detail/MySubmissions/index.jsx
src/shared/components/challenge-detail/Submissions/index.jsx
src/shared/containers/Dashboard/index.jsx
src/shared/containers/EmailVerification/index.jsx
src/shared/containers/Settings.jsx
src/shared/reducers/tc-communities/index.js
src/shared/utils/tc.js

Updated tc-auth-lib name

---

src/shared/components/challenge-listing/Listing/Bucket/index.jsx
src/shared/components/challenge-listing/Listing/index.jsx

fix(challenge-listing): add NO_LIVE_CHALLENGES messsage to All bucket in case of 0 challenges

---

src/shared/components/challenge-detail/Specification/index.jsx

Challenge Details - Fix allowStockArt to design track

---

src/shared/components/challenge-listing/Filters/FiltersPanel/index.jsx

Fix the side impact on the issue 4976

fix side impact

---

src/server/tc-communities/blockchain/metadata.json
src/server/tc-communities/cognitive/metadata.json
src/server/tc-communities/comcast/metadata.json
src/server/tc-communities/cs/metadata.json
src/server/tc-communities/iot/metadata.json
src/server/tc-communities/mobile/metadata.json
src/server/tc-communities/tco19/metadata.json
src/server/tc-communities/tco20/metadata.json
src/server/tc-communities/tco21/metadata.json
src/server/tc-communities/veterans/metadata.json
src/server/tc-communities/wipro/metadata.json
src/server/tc-communities/zurich/metadata.json
src/shared/components/challenge-listing/Filters/FiltersPanel/index.jsx

Hide cognitive and blockchain from dropdown filter

---

src/server/services/communities.js

Issue: #5048 
Dependency: https://github.com/topcoder-platform/community-app/pull/5054

Added hideFIlter to getList

---

src/shared/components/challenge-detail/Header/index.jsx

fix: for issue #4256

---

src/shared/components/challenge-detail/Header/ChallengeTags.jsx
src/shared/components/challenge-listing/Filters/ChallengeFilters.jsx
src/shared/components/challenge-listing/Filters/FiltersPanel/index.jsx
src/shared/reducers/challenge-listing/index.js
src/shared/utils/challenge-listing/buckets.js

Fix blank page issue when filtering challenge listing by clicking on challenge type tag below the title in challenge detail page.
#5050

fix: issue #5050

---

src/shared/components/challenge-listing/Sidebar/BucketSelector/index.jsx
src/shared/containers/challenge-listing/Listing/index.jsx

Hide onGoing bucket

---

src/shared/components/challenge-detail/Header/ChallengeTags.jsx
src/shared/components/challenge-listing/Listing/Bucket/index.jsx
src/shared/containers/challenge-detail/index.jsx

Reset previous type/tag filter when clicking type/tag in challenge detail page.
#5050

fix: update for issue #5050

---

src/shared/containers/challenge-listing/Listing/index.jsx

Fix Sub-community challenge listing filter

---

src/server/tc-communities/blockchain/metadata.json
src/server/tc-communities/cognitive/metadata.json
src/shared/components/challenge-listing/Filters/ChallengeFilters.jsx

Sub-communities : Disable filter by default and fix filter counter

---

__tests__/shared/components/challenge-listing/Sidebar/__snapshots__/index.jsx.snap
src/shared/components/challenge-listing/Sidebar/index.jsx

issue 5093 fix

---

src/shared/components/challenge-detail/Header/DeadlinesPanel/Card/index.jsx

issue 3215 fix

---

src/shared/components/challenge-listing/Filters/FiltersPanel/index.jsx

issue 5071 fix

---

src/shared/components/challenge-listing/Listing/Bucket/index.jsx
src/shared/components/challenge-listing/Listing/index.jsx

fix: no challenges message when sorting all challenges

---

src/shared/components/challenge-listing/Filters/FiltersPanel/style.scss

https://github.com/topcoder-platform/community-app/issues/5072

issue-5072

---

src/shared/containers/Dashboard/index.jsx

fix: empty values in dashboard sub-community

---

package.json
src/shared/containers/challenge-detail/index.jsx

Issue; #5121 
Dependency: https://github.com/topcoder-platform/topcoder-react-lib/pull/275

Pass legacyid to v2 results call

---

src/shared/containers/challenge-detail/index.jsx
src/shared/containers/challenge-listing/Listing/index.jsx
src/shared/routes/Topcoder/ChallengeListing.jsx

SEO: Update Challenge Listing and Details

---

.circleci/config.yml
package.json

Issue: #5159 
Dependency: https://github.com/topcoder-platform/topcoder-react-lib/pull/279

Smoke Testing 2020-11-05 : Auth0 hotfix

---

__tests__/shared/components/ChallengeTile/__snapshots__/index.jsx.snap
src/shared/components/ChallengeTile/index.jsx

fix: #5082 blank page on clicking challenges tab from stats history page

---

src/shared/components/Contentful/PasswordScreen/style.scss
src/shared/routes/index.jsx

https://github.com/topcoder-platform/community-app/issues/5164

Apollo site url patch

---

src/shared/components/Terms/TermDetails.scss

fix: rendering of ordered list numbering and unordered list bullet

---

src/shared/actions/page/challenge-details.js
src/shared/components/challenge-detail/Checkpoints/index.jsx
src/shared/containers/challenge-detail/index.jsx
src/shared/reducers/page/challenge-details.js

fix: toggle checkpoint feedback

---

.circleci/config.yml
__tests__/shared/components/ChallengeTile/__snapshots__/index.jsx.snap
__tests__/shared/components/SubmissionManagement/Submission.jsx
__tests__/shared/components/SubmissionManagement/__snapshots__/Submission.jsx.snap
src/shared/actions/page/challenge-details.js
src/shared/components/ChallengeTile/index.jsx
src/shared/components/SubmissionManagement/Submission/index.jsx
src/shared/components/challenge-detail/Checkpoints/index.jsx
src/shared/components/challenge-listing/Filters/FiltersPanel/index.jsx
src/shared/containers/SubmissionManagement/index.jsx
src/shared/containers/challenge-detail/index.jsx
src/shared/reducers/page/challenge-details.js

Issues: #1532 #4212 #5082 #5125

Smoke Testing 2020/11/10 - BugBash issues

---

src/shared/components/challenge-detail/Header/TabSelector/index.jsx

Issue: #5041 
Fix logical if user registered.

Hotfix - Smoke Testing 2020/11/12 - New forums

---

src/shared/components/Contentful/Route.jsx
src/shared/components/MetaTags.jsx
src/shared/components/Settings/index.jsx
src/shared/containers/EDU/Home.jsx
src/shared/containers/EDU/Search.jsx
src/shared/containers/EDU/Tracks.jsx
src/shared/containers/EDU/styles/home.scss
src/shared/containers/EDU/styles/search.scss
src/shared/containers/EDU/styles/tracks.scss
src/shared/containers/GigsPages.jsx
src/shared/containers/Profile.jsx
src/shared/containers/ProfileStats.jsx
src/shared/containers/challenge-detail/index.jsx
src/shared/containers/challenge-listing/Listing/index.jsx
src/shared/containers/terms-detail/index.jsx
src/shared/routes/Communities/Blockchain/Routes.jsx
src/shared/routes/Communities/Cognitive/Routes.jsx
src/shared/routes/Communities/Mobile/Routes.jsx
src/shared/routes/EDUHome.jsx
src/shared/routes/EDUSearch.jsx
src/shared/routes/EDUTracks.jsx
src/shared/routes/GigsPages.jsx
src/shared/routes/Topcoder/Routes.jsx
src/shared/routes/index.jsx

Challenge: https://www.topcoder.com/challenges/ba9ddd0e-27d7-4040-a602-ed2ee24cd08d
Issues: #5016 #4544

Implement SEO to Gig and Thrive pages and move MetaTags from lib

---

src/shared/containers/challenge-detail/index.jsx

Fix title in social SEO

---

.circleci/config.yml
config/default.js
config/production.js
src/shared/components/challenge-detail/Header/TabSelector/index.jsx

Smoke Testing 2020/11/24 - Submission review

---

.circleci/config.yml
src/shared/components/HallOfFamePage/HoF.jsx
src/shared/components/HallOfFamePage/styles.scss

Spirit award

---

.circleci/config.yml
src/shared/components/challenge-listing/Filters/ChallengeFilters.jsx
src/shared/components/challenge-listing/Filters/FiltersPanel/index.jsx
src/shared/containers/challenge-listing/Listing/index.jsx
src/shared/utils/challenge-listing/buckets.js

Listing search

---

.circleci/config.yml
src/shared/containers/challenge-detail/index.jsx

Show challenge name title in Social og:title

---

.circleci/config.yml
src/shared/components/challenge-detail/Specification/index.jsx

Implemented private spec

---

.circleci/config.yml
src/shared/components/challenge-listing/Filters/ChallengeSearchBar/index.jsx
src/shared/containers/challenge-listing/ChallengeSearchBar.jsx

Challenge listing - Fix whitespace in search field

---

src/shared/containers/challenge-listing/FilterPanel.jsx

https://github.com/topcoder-platform/community-app/issues/5259

fix for #5259 - using saved challenge types in filter state

---

.circleci/config.yml
__tests__/shared/components/__snapshots__/TopcoderFooter.jsx.snap
__tests__/shared/components/challenge-listing/Sidebar/__snapshots__/Footer.jsx.snap
src/shared/components/Dashboard/CurrentActivity/Header/index.jsx
src/shared/components/Dashboard/CurrentActivity/index.jsx
src/shared/reducers/page/dashboard.js

Hide My Communities from My Dashboard

---

__tests__/shared/components/__snapshots__/TopcoderFooter.jsx.snap
__tests__/shared/components/challenge-listing/Sidebar/__snapshots__/Footer.jsx.snap

Fix footer snapshots

---

.circleci/config.yml
CODEOWNERS

CI Manual Approval

---

.circleci/config.yml
package.json

Issue: https://github.com/topcoder-platform/community-app/issues/5314
Dependency: https://github.com/topcoder-platform/topcoder-react-lib/pull/294

Smoke Testing 2021/01/26 - Fix challenges listing

---

.circleci/config.yml
__tests__/shared/components/Settings/Preferences/Email/__snapshots__/index.jsx.snap
package-lock.json
src/server/routes/mailchimp.js
src/server/services/mailchimp.js
src/shared/actions/newsletterPreferences.js
src/shared/components/NewsletterSignupForMembers/ConfirmModal/style.scss
src/shared/components/Settings/Preferences/Email/index.jsx
src/shared/components/Settings/Preferences/Email/styles.scss
src/shared/components/Settings/ToggleableItem/index.jsx
src/shared/containers/EmailSubscribeForm/index.jsx
src/shared/containers/NewsletterPreferences.jsx
src/shared/containers/NewsletterSignupForMembers.jsx
src/shared/reducers/newsletterPreferences.js

Reverts topcoder-platform/community-app#5348

Revert "Email pref revamp"

---

.circleci/config.yml
__tests__/shared/components/Header/__snapshots__/index.jsx.snap
__tests__/shared/components/__snapshots__/TopcoderFooter.jsx.snap
config/default.js
config/production.js
src/shared/components/TopcoderFooter/index.jsx

Forums on top navigation should take use to Vanilla Forums

---

.circleci/config.yml
src/server/tc-communities/wipro/metadata.json

https://github.com/topcoder-platform/community-app/issues/5367

Update nav item for TopGear

---

src/shared/actions/recruitCRM.js
src/shared/components/Gigs/GigApply/index.jsx
src/shared/components/Gigs/GigDetails/index.jsx
src/shared/components/Gigs/LoginModal/index.jsx
src/shared/components/Gigs/ReferralModal/index.jsx
src/shared/utils/gigs.js

Gigwork updates

---

.circleci/config.yml
src/shared/containers/tco/Leaderboard/ChallengeHistoryModal/index.jsx

Tco leaderboard fix

---

.circleci/config.yml
src/assets/images/checkmark-green.svg
src/server/services/recruitCRM.js
src/shared/actions/recruitCRM.js
src/shared/components/GUIKit/Assets/Styles/Includes/_mixin.scss
src/shared/components/GUIKit/DropdownTerms/index.jsx
src/shared/components/GUIKit/TextInput/index.jsx
src/shared/components/GUIKit/TextInput/style.scss
src/shared/components/Gigs/GigApply/index.jsx
src/shared/components/Gigs/GigApply/style.scss
src/shared/components/Gigs/LoginModal/modal.scss
src/shared/containers/Gigs/RecruitCRMJobApply.jsx
src/shared/reducers/recruitCRM.js
src/shared/services/recruitCRM.js

Gig application update

---

config/default.js
src/shared/components/challenge-detail/Specification/SideBar/index.jsx

Bug bash issue-5329 - add templates repo link to sidebar

---

src/shared/components/challenge-detail/Winners/Winner/index.jsx

#5248 fix "window is not defined" error when accessing challenge detail tab directly using URL parameter

Fix for issue #5248 - window is not defined error

---

.circleci/config.yml
__tests__/shared/components/challenge-listing/__snapshots__/index.jsx.snap
src/shared/components/challenge-listing/index.jsx
src/shared/components/challenge-listing/style.scss
src/shared/containers/challenge-detail/index.jsx
src/shared/containers/challenge-detail/styles.scss

Outage banner

---

__tests__/shared/components/challenge-listing/__snapshots__/index.jsx.snap
src/shared/components/challenge-listing/index.jsx
src/shared/containers/challenge-detail/index.jsx

(hotfix) Outage banner - change start / end time.

---

.circleci/config.yml
__tests__/shared/components/challenge-listing/__snapshots__/index.jsx.snap
src/shared/components/challenge-listing/index.jsx
src/shared/components/challenge-listing/style.scss
src/shared/containers/challenge-detail/index.jsx
src/shared/containers/challenge-detail/styles.scss

Remove outage banner

---

config/default.js
config/development.js
src/assets/images/banner-close.svg
src/assets/images/banner-info.svg
src/shared/components/challenge-listing/Banner/index.jsx
src/shared/components/challenge-listing/Banner/style.scss
src/shared/components/challenge-listing/index.jsx

Add banner on Listings Page to introduce MFE

---

.circleci/config.yml
src/shared/components/Contentful/Tabs/Tabs.jsx

Contentful tabs fix

---

package.json

Release v1.9.3

---

.circleci/config.yml
src/shared/components/Gigs/GigDetails/index.jsx

Gig skills title

---

.circleci/config.yml
src/shared/containers/tc-communities/Loader.jsx
src/shared/routes/Communities/Wipro/Routes.jsx

https://github.com/topcoder-platform/community-app/issues/5565

(hotfix) TopGear redirect

---

.circleci/config.yml
src/shared/components/Settings/Profile/BasicInfo/index.jsx

https://github.com/topcoder-platform/community-app/milestone/120

Release v1.10.1

---

.circleci/config.yml
automated-smoke-test/conf.ts
automated-smoke-test/config/automation-config-beta.json
automated-smoke-test/config/automation-config-prod.json
automated-smoke-test/config/automation-config-staging.json

Automated Smoke Testing - Member Profile

---

src/server/tc-communities/index.js
src/shared/reducers/terms.js

tc-communities API: Additional logging

---

.circleci/config.yml
src/server/tc-communities/index.js
src/shared/reducers/terms.js

Terms: Fix __community__ page check

---

.circleci/config.yml
__tests__/shared/components/Leaderboard/__snapshots__/PodiumSpot.jsx.snap
src/shared/components/Leaderboard/ChallengeHistoryModal/index.jsx
src/shared/components/Leaderboard/ChallengeHistoryModal/styles.scss
src/shared/components/Leaderboard/LeaderboardTable/index.jsx
src/shared/components/Leaderboard/LeaderboardTable/themes/tco22.scss
src/shared/components/Leaderboard/PodiumSpot/index.jsx
src/shared/components/Leaderboard/PodiumSpot/themes/styles.scss
src/shared/components/Leaderboard/PodiumSpot/themes/tco20.scss
src/shared/components/Leaderboard/PodiumSpot/themes/tco22.scss
src/shared/components/Leaderboard/avatarStyles.scss
src/shared/containers/tco/Leaderboard/themes/styles.scss

New leaderboards theme

---

.circleci/config.yml
src/shared/utils/challenge-listing/helper.js

Fix challenge end date

---

src/shared/components/Contentful/MemberTalkCloud/MemberTalkCloud.jsx
src/shared/components/Contentful/MemberTalkCloud/index.jsx
src/shared/components/Contentful/MemberTalkCloud/themes/default.scss
src/shared/components/Contentful/Viewport/index.jsx
src/shared/components/examples/MemberTalkCloudExample/index.jsx
src/shared/components/examples/MemberTalkCloudExample/style.scss
src/shared/routes/Examples/Examples.jsx

Talk cloud component

---

.circleci/config.yml
config/default.js
package-lock.json
package.json
src/shared/components/ProfilePage/Stats/HistoryGraph/index.jsx
src/shared/components/ProfilePage/StatsCategory/index.jsx
src/shared/components/ProfilePage/index.jsx
src/shared/containers/Profile.jsx
src/shared/containers/ProfileStats.jsx
src/shared/utils/memberStats.js

Issues: #5663 #5656 
Dependency: https://github.com/topcoder-platform/topcoder-react-lib/pull/313
- update user profile page to use v5 /stats and /stats/history endpoints (stats/distribution is still v3)
- v5 stats endpoints are auth protected so unauthenticated users can no longer see private community stats
- configured priviate community redirects public members profile page to community app
- configured private community redirects from community app profile page to private community app profile page

feature(profile): redirect between private community and public community profile page

---

.circleci/config.yml
src/shared/containers/tc-communities/Loader.jsx

Topgear challenge redirect

---

.circleci/config.yml
src/shared/containers/Profile.jsx

fix: keep users with @topcoder.com email on their profile page

---

.gitignore
src/shared/services/recruitCRM.js

Reverts topcoder-platform/community-app#5687

Revert "Earn Restructure Dev Deploy"

---

.circleci/config.yml
src/shared/components/Gigs/ReferralCode/index.jsx
src/shared/components/Gigs/ReferralCode/style.scss
src/shared/containers/GigsPages.jsx

Slash gigs updates

---

.circleci/config.yml
src/shared/components/challenge-detail/Specification/SideBar/index.jsx

Issue: https://github.com/topcoder-platform/community-app/issues/5691
cc @Oanh-and-only-Oanh 
Adding new link to the sidebar

feature:link-thrive add sidebar link to thrive article

---

.gitignore
src/shared/services/recruitCRM.js

Reverts topcoder-platform/community-app#5693

Earn Restructure Dev Deploy Changes

---

.circleci/config.yml
config/default.js
package-lock.json
package.json
src/server/routes/recruitCRM.js
src/server/services/recruitCRM.js
src/shared/actions/recruitCRM.js
src/shared/components/Gigs/ReferralCode/index.jsx
src/shared/containers/Gigs/RecruitCRMJobApply.jsx
src/shared/containers/Gigs/RecruitCRMJobs.jsx
src/shared/services/recruitCRM.js

Gig cache layer

---

.circleci/config.yml
src/server/index.js

Remove X-Frame-Options from DocuSign request

---

src/server/services/recruitCRM.js

[Add Log] Log the referralId  (#5776)

---

.circleci/config.yml
src/shared/components/Contentful/Tabs/Tabs.jsx
src/shared/components/Contentful/Tabs/index.jsx
src/shared/components/Contentful/Tabs/themes/pills.scss
src/shared/components/Contentful/Tabs/themes/vertical.scss

Contentful tabs mobile

---

.circleci/config.yml
src/shared/components/Contentful/ArticleCard/themes/article_small.scss
src/shared/containers/EDU/Search.jsx
src/shared/containers/EDU/styles/tracks.scss

Thrive spooky1 p0 3

---

.circleci/config.yml
__tests__/shared/components/Settings/Account/__snapshots__/index.jsx.snap
__tests__/shared/components/Settings/Account/index.jsx
src/shared/components/Settings/Account/LinkedAccount/AddWebLink.jsx
src/shared/components/Settings/Account/LinkedAccount/index.jsx
src/shared/components/Settings/Account/index.jsx
src/shared/components/Settings/Profile/BasicInfo/index.jsx
src/shared/components/Settings/Profile/Education/index.jsx
src/shared/components/Settings/Profile/Education/styles.scss
src/shared/components/Settings/Profile/Hobby/index.jsx
src/shared/components/Settings/Profile/Work/index.jsx
src/shared/components/Settings/Tools/Devices/index.jsx
src/shared/reducers/page/ui/settings.js

https://github.com/topcoder-platform/community-app/issues?q=is%3Aissue+is%3Aopen+label%3Atcx_FixAccepted

[Bug Bash] Fixes I

---

src/shared/components/InputSelect/index.jsx

issue #5879

---

src/shared/components/Settings/Profile/Language/index.jsx

issue #5870

---

.circleci/config.yml
automated-smoke-test/page-objects/pages/topcoder/challenge-detail/challenge-detail.helper.ts

AST - Fix timeline test form challenge sample

---

.circleci/config.yml
package.json

Issue: https://github.com/topcoder-platform/community-app/issues/5935
Dependency:
https://github.com/topcoder-platform/community-app/pull/5936 
https://github.com/topcoder-platform/community-app/pull/5937 
https://github.com/topcoder-platform/topcoder-react-lib/pull/324/

Fix topcoder-react-lib

---

.circleci/config.yml
package-lock.json
src/shared/components/Settings/Profile/BasicInfo/index.jsx

Issue: https://github.com/topcoder-platform/community-app/issues/5918
Dependency: https://github.com/topcoder-platform/topcoder-react-lib/pull/327

feat: use v5 member api to save traits

---

.circleci/config.yml
__tests__/shared/components/__snapshots__/TopcoderFooter.jsx.snap
__tests__/shared/components/challenge-listing/Sidebar/__snapshots__/Footer.jsx.snap
package-lock.json
package.json
src/shared/components/Gigs/GigApply/index.jsx
src/shared/components/Gigs/LoginModal/index.jsx
src/shared/components/Gigs/ReferralModal/index.jsx
src/shared/components/Settings/Profile/BasicInfo/index.jsx
src/shared/reducers/page/settings.js

* use v5 apis in settings page
* include regSource=gigs when registration is initiated from Gigs page modal

feat: v5-settings upgrade

---

src/shared/components/Settings/Profile/BasicInfo/index.jsx

fix issue 5954

---

.circleci/config.yml
src/shared/components/Settings/Profile/BasicInfo/index.jsx

fix: settings save fail

---

.circleci/config.yml
src/shared/components/Settings/Profile/BasicInfo/index.jsx
src/shared/containers/challenge-detail/index.jsx

MS: https://github.com/topcoder-platform/micro-frontends-onboarding-app/milestone/3

Release v1.15.6

---

.circleci/config.yml
__tests__/shared/components/SubmissionManagement/__snapshots__/Submission.jsx.snap
package.json
src/shared/components/SubmissionManagement/Submission/index.jsx
src/shared/utils/tc.js

Issue: https://github.com/topcoder-platform/community-app/issues/6059

fix: disable download of infected submissions

---

.circleci/config.yml
src/server/services/recruitCRM.js

https://topcoder.atlassian.net/browse/VULN-2460

Gig recruit - Sanitize jobs API

---

src/shared/containers/Profile.jsx

Issue: https://github.com/topcoder-platform/community-app/issues/6029

Return 404 if member not ACTIVE

---

config/default.js
config/production.js
src/shared/components/challenge-detail/ThriveArticles/index.jsx

Issue: https://github.com/topcoder-platform/community-app/issues/6063

Fix thrive url

---

src/shared/components/challenge-detail/Specification/styles.scss

Issue: https://github.com/topcoder-platform/community-app/issues/6289#issuecomment-1106002284

Challenge Details - Fix spec  width

---

src/server/services/recruitCRM.js
src/shared/reducers/recruitCRM.js

Issue: https://github.com/topcoder-platform/community-app/issues/6317

Sanitize Jobs API

---

.circleci/config.yml
package.json

Issue: https://github.com/topcoder-platform/community-app/issues/6311
Dependency: https://github.com/topcoder-platform/topcoder-react-lib/pull/336

Pv challenge msg

---

src/shared/components/ProfilePage/Stats/ChartTooltip/index.jsx
src/shared/components/ProfilePage/Stats/HistoryGraph/index.jsx

Reverts topcoder-platform/community-app#6322

Revert "Revert "fix: fix challenge link for marathon match in member statics page""

---

config/default.js
config/production.js
src/shared/containers/SubmissionManagement/index.jsx

Reverts topcoder-platform/community-app#6325

Revert "fix: issue #5582"

---

.circleci/config.yml
src/shared/components/ProfilePage/Stats/ChartTooltip/index.jsx
src/shared/components/ProfilePage/Stats/HistoryGraph/index.jsx

fix: fix challenge link for marathon in member statics from feedback

fix: fix challenge link for marathon in member statics from feedback

---

.circleci/config.yml
Dockerfile
package-lock.json

Issue: https://github.com/topcoder-platform/community-app/issues/6349
Fix for bug reported on NPM https://github.com/npm/cli/issues/4896

CircleCI Git URL fix

---

.circleci/config.yml
__tests__/shared/components/__snapshots__/TopcoderFooter.jsx.snap
package-lock.json
src/shared/components/Contentful/Route.jsx
src/shared/components/TopcoderFooter/index.jsx

Footer update

---

.circleci/config.yml
package.json

Issue: https://topcoder.atlassian.net/browse/PROD-2097

Increase node memory

---

__tests__/shared/components/ProfilePage/__snapshots__/index.jsx.snap
src/shared/components/ProfilePage/Header/index.jsx

PR for Verified Badge
https://topcoder.atlassian.net/browse/PROD-2155

improvement(reskin-profile): verified badge

---

__tests__/shared/components/__snapshots__/Content.jsx.snap
src/server/services/communities.js
src/shared/components/Content/index.jsx

Milestone: https://github.com/topcoder-platform/community-app/milestone/176 
community-app
> Issues: [PROD-2155](https://topcoder.atlassian.net/browse/PROD-2155)

Release v1.17.7

---

src/shared/components/challenge-listing/Filters/FiltersPanel/index.jsx

fix: issue #6579

---

src/shared/components/challenge-listing/Filters/FiltersPanel/index.jsx
src/shared/components/challenge-listing/Listing/Bucket/index.jsx
src/shared/utils/challenge-listing/buckets.js

fix: issue #6581

---

src/shared/components/challenge-listing/Filters/FiltersPanel/index.jsx

feat: show tco toggle

---

.circleci/config.yml
src/server/index.js

Reverts topcoder-platform/community-app#6586

Revert "remove unsafe-inline csp for veterans"

---

.circleci/config.yml
package.json

Issue: https://topcoder.atlassian.net/browse/PROD-1875
Dependency: https://github.com/topcoder-platform/topcoder-react-lib/pull/350

Database conversion of old MM ids to new challenge IDs

---

.circleci/config.yml
package.json

Issue: https://topcoder.atlassian.net/browse/PROD-1875
Dependency: https://github.com/topcoder-platform/topcoder-react-lib/pull/353

Release v1.17.16

---

src/shared/components/challenge-detail/Header/TabSelector/index.jsx
src/shared/components/challenge-detail/Submissions/index.jsx
src/shared/containers/challenge-detail/index.jsx

https://topcoder.atlassian.net/browse/PROD-2872

Enable dashboard on data science

---

.circleci/config.yml
src/shared/components/Settings/ExperienceAndSkills/WorkSkills/Skills/AddSkillsModal/index.jsx

https://topcoder.atlassian.net/browse/PROD-2937

Reskin profile settings

---

src/shared/containers/timeline-wall/index.jsx
src/shared/containers/timeline-wall/pending-approvals/approval-item/index.jsx
src/shared/containers/timeline-wall/pending-approvals/styles.scss
src/shared/containers/timeline-wall/photo-items-mobile/index.jsx
src/shared/containers/timeline-wall/timeline-events/events/event-item/index.jsx
src/shared/containers/timeline-wall/timeline-events/styles.scss

fix mobile thumbnail

---

__tests__/shared/components/challenge-listing/Filters/__snapshots__/FiltersPanel.jsx.snap
__tests__/shared/components/challenge-listing/Sidebar/__snapshots__/index.jsx.snap
__tests__/shared/components/challenge-listing/__snapshots__/index.jsx.snap
automated-smoke-test/page-objects/pages/topcoder/challenge-listing/challenge-listing.helper.ts
src/shared/components/challenge-listing/Filters/FiltersPanel/index.jsx
src/shared/components/challenge-listing/Listing/ReviewOpportunityBucket/index.jsx
src/shared/components/challenge-listing/Listing/index.jsx
src/shared/components/challenge-listing/Sidebar/BucketSelector/Bucket/index.jsx
src/shared/components/challenge-listing/Sidebar/BucketSelector/Bucket/style.scss
src/shared/components/challenge-listing/Sidebar/BucketSelector/index.jsx
src/shared/components/challenge-listing/Sidebar/index.jsx
src/shared/components/challenge-listing/index.jsx
src/shared/containers/challenge-listing/Listing/index.jsx
src/shared/containers/challenge-listing/Sidebar.jsx
src/shared/reducers/challenge-listing/index.js
src/shared/utils/challenge-listing/buckets.js
src/shared/utils/challenge-listing/helper.js

Reverts topcoder-platform/community-app#6708

Revert "Prod 2993"

---

src/shared/containers/timeline-wall/timeline-events/add-event/index.jsx

https://github.com/topcoder-platform/timeline-wall-api/issues/9

fix: change new event labels

---

src/shared/containers/timeline-wall/pending-approvals/approval-item/index.jsx
src/shared/containers/timeline-wall/timeline-events/events/event-item/index.jsx

https://github.com/topcoder-platform/timeline-wall-api/issues/10

fix: linked handles

---

config/default.js

https://github.com/topcoder-platform/timeline-wall-api/issues/7

fix: dropdown options for rejection of submission

---

config/default.js
src/shared/containers/timeline-wall/index.jsx
src/shared/containers/timeline-wall/styles.scss

[PROD-2095](https://topcoder.atlassian.net/browse/PROD-2095)

Timeline Wall - fixed forum link

---

src/shared/containers/timeline-wall/styles.scss
src/shared/containers/timeline-wall/timeline-events/right-filter/styles.scss

https://github.com/topcoder-platform/timeline-wall-api/issues/20
https://github.com/topcoder-platform/timeline-wall-api/issues/25#issuecomment-1324034113

Issue 20 + 25: navigation should not go below footer

---

src/shared/containers/timeline-wall/timeline-events/right-filter/styles.scss
src/shared/containers/timeline-wall/timeline-events/styles.scss

https://github.com/topcoder-platform/timeline-wall-api/issues/20

fix: navigation should not go below footer

---

src/shared/containers/timeline-wall/index.jsx

https://github.com/topcoder-platform/timeline-wall-api/issues/29

fix: set initial value of sidebar navigation to current year

---

.circleci/config.yml

Sync with develop

---

__tests__/shared/components/Settings/Preferences/Email/__snapshots__/index.jsx.snap
src/shared/components/Settings/Preferences/Email/data.jsx
src/shared/components/Settings/Preferences/Email/index.jsx
src/shared/components/Settings/Preferences/List/Item/index.jsx
src/shared/components/Settings/Preferences/List/Item/styles.scss
src/shared/components/Settings/Preferences/List/data.jsx

https://topcoder.atlassian.net/browse/PROD-3059

fix: mailchimp subscribe issues

---

config/default.js
package-lock.json
package.json
src/shared/containers/SubmissionPage.jsx

Added config. Ready for DEV and PROD.
https://topcoder.atlassian.net/browse/PROD-3279

Prod 3279 sprig challenge survey

---

config/production.js

https://topcoder.atlassian.net/browse/PLAT-2037

Added SPRIG_ENVIRONMENT_ID to prod

---

.circleci/config.yml
config/production.js
src/shared/components/Settings/ExperienceAndSkills/WorkSkills/Skills/AddSkillsModal/index.jsx
src/shared/components/Settings/ExperienceAndSkills/WorkSkills/Skills/AddSkillsModal/styles.scss
src/shared/components/Settings/ExperienceAndSkills/WorkSkills/Skills/index.jsx

Milestone: https://github.com/topcoder-platform/community-app/milestone/206 
community-app
> Issues: [GAME-224](https://topcoder.atlassian.net/browse/GAME-224)

Release v1.20.1

---

.circleci/config.yml
src/shared/components/challenge-detail/Header/index.jsx

Milestone: https://github.com/topcoder-platform/community-app/milestone/210 
community-app
> Issues: [PROD-3521](https://topcoder.atlassian.net/browse/PROD-3521)
[PROD-3521]: https://topcoder.atlassian.net/browse/PROD-3521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Release v1.20.4

---

src/shared/components/TopcoderFooter/index.jsx
src/shared/containers/TopcoderHeader.jsx

https://topcoder.atlassian.net/browse/PROD-3771
https://topcoder.atlassian.net/browse/PROD-3777
PROD-3777 - improve uninav loading time
PROD-3771 - load footer type based on url param

PROD-3777 universal nav load

---

__tests__/shared/components/__snapshots__/TopcoderFooter.jsx.snap
src/shared/components/TopcoderFooter/index.jsx
src/shared/containers/TopcoderHeader.jsx

https://topcoder.atlassian.net/browse/PROD-3881
Re-render uninav on sub pages & persist nav type in session storage

PROD-3881 universal nav

---

src/shared/components/challenge-detail/Header/index.jsx

Reverts topcoder-platform/community-app#6793
https://topcoder.atlassian.net/browse/PROD-3490

Revert "PROD-3490"

---

package-lock.json
package.json

Updates the loader package for the uninav

update uninav loader

---

.eslintrc
src/shared/components/Contentful/AppComponent/index.jsx
src/shared/components/Contentful/Viewport/index.jsx
src/shared/components/Gigs/ReferralCode/index.jsx
src/shared/components/Settings/Account/LinkedAccount/ExistingLink.jsx
src/shared/components/challenge-detail/Header/TabSelector/index.jsx
src/shared/components/challenge-detail/Submissions/SubmissionRow/SubmissionHistoryRow/index.jsx
src/shared/components/challenge-detail/Submissions/SubmissionRow/index.jsx
src/shared/components/challenge-detail/Submissions/index.jsx
src/shared/components/challenge-detail/Winners/Winner/index.jsx
src/shared/components/challenge-detail/Winners/index.jsx
src/shared/components/challenge-listing/ChallengeCard/Prize/index.jsx
src/shared/components/tc-communities/AccessDenied/index.jsx
src/shared/components/tc-communities/communities/wipro/Home/index.jsx
src/shared/containers/ErrorIcons/index.jsx
src/shared/containers/challenge-detail/index.jsx
src/shared/utils/challenge.js

Revert RDM submission download changes for further QA

Revert RDM submission download changes for further QA

---

.eslintrc
src/shared/components/Contentful/AppComponent/index.jsx
src/shared/components/Contentful/Viewport/index.jsx
src/shared/components/Gigs/ReferralCode/index.jsx
src/shared/components/Settings/Account/LinkedAccount/ExistingLink.jsx
src/shared/components/challenge-detail/Header/TabSelector/index.jsx
src/shared/components/challenge-detail/Submissions/SubmissionRow/SubmissionHistoryRow/index.jsx
src/shared/components/challenge-detail/Submissions/SubmissionRow/index.jsx
src/shared/components/challenge-detail/Submissions/index.jsx
src/shared/components/challenge-detail/Winners/Winner/index.jsx
src/shared/components/challenge-detail/Winners/index.jsx
src/shared/components/challenge-listing/ChallengeCard/Prize/index.jsx
src/shared/components/tc-communities/AccessDenied/index.jsx
src/shared/components/tc-communities/communities/wipro/Home/index.jsx
src/shared/containers/ErrorIcons/index.jsx
src/shared/containers/challenge-detail/index.jsx
src/shared/utils/challenge.js

Reverts topcoder-platform/community-app#6841

Revert "Revert RDM submission download changes for further QA --> Prod"

---

.circleci/config.yml
package-lock.json
package.json

Applications on Gigs are not reflecting into the system due to API error
https://topcoder.atlassian.net/browse/PROD-4165

Gigs applications fix

---

src/shared/components/challenge-detail/Winners/Winner/index.jsx

https://topcoder.atlassian.net/browse/PROD-4178

PROD - Hotfix for download not working on individual winner

---

.circleci/config.yml
src/shared/components/Gigs/GigApply/index.jsx
src/shared/components/Gigs/LoginModal/index.jsx
src/shared/components/Gigs/ReferralModal/index.jsx
src/shared/components/LoginModal/index.jsx

Hot fix for PROD-4234

---

.circleci/config.yml
src/shared/components/Settings/Account/Security/index.jsx
src/shared/components/Settings/Account/Security/styles.scss
src/shared/services/money.js

https://topcoder.atlassian.net/browse/PROD-4276
https://topcoder.atlassian.net/browse/PROD-4277

PROD - FIx when currency endpoint down / Add 'i' to Dice ID switch

---

.circleci/config.yml
src/shared/containers/ContentfulLoader.jsx

Fix for contentful not loading properly, related to PROD-4301

Hotfix contentful not working june222023

---

.circleci/config.yml
src/server/index.js

https://topcoder.atlassian.net/browse/PROD-4317

Prod 4317 -> dev

---

.circleci/config.yml
src/shared/containers/TopcoderHeader/index.jsx

Profile pics not showing up in the header

Fix for MP-327

---

.circleci/config.yml
src/server/index.js
src/shared/containers/TopcoderHeader/index.jsx

https://topcoder.atlassian.net/browse/MP-327

PROD - deploy fix for MP-327

---

.circleci/config.yml
src/shared/components/GUIKit/PhotoVideoItem/index.jsx
src/shared/components/GUIKit/PhotoVideoItem/styles.scss
src/shared/containers/timeline-wall/modal-photo-viewer/index.jsx
src/shared/containers/timeline-wall/pending-approvals/approval-item/index.jsx
src/shared/containers/timeline-wall/photo-items-mobile/index.jsx
src/shared/containers/timeline-wall/photo-items-mobile/styles.scss
src/shared/containers/timeline-wall/timeline-events/events/event-item/index.jsx

https://topcoder.atlassian.net/browse/PROD-4251

PROD-4251 -> develop

---

src/shared/services/skills.js

Fix endpoint for https://topcoder.atlassian.net/browse/TSJR-118

HOTFIX - wrong skills autocomplete endpoint used

---

.circleci/config.yml
config/backup-default.js
config/default.js
config/production.js
src/shared/components/GUIKit/DropdownSingleSkills/index.jsx
src/shared/components/GUIKit/DropdownSingleSkills/style.scss
src/shared/components/GUIKit/JobListCard/index.jsx
src/shared/components/GUIKit/SearchCombo/index.jsx
src/shared/components/GUIKit/SearchCombo/style.scss
src/shared/components/challenge-detail/Header/ChallengeTags.jsx
src/shared/components/challenge-detail/Header/index.jsx
src/shared/components/challenge-detail/Header/style.scss
src/shared/components/challenge-detail/RecommendedActiveChallenges/ChallengesCard/index.jsx
src/shared/components/challenge-listing/ChallengeCard/Status/index.jsx
src/shared/components/challenge-listing/ChallengeCard/index.jsx
src/shared/components/challenge-listing/ReviewOpportunityCard/index.jsx
src/shared/components/challenge-listing/Tags.jsx
src/shared/components/challenge-listing/style.scss
src/shared/containers/Gigs/RecruitCRMJobs.jsx
src/shared/utils/challenge-detail/helper.jsx

https://topcoder.atlassian.net/browse/TSJR-310
https://topcoder.atlassian.net/browse/TSJR-204

Deploy 29 nov

---

src/shared/components/challenge-detail/Header/ChallengeTags.jsx
src/shared/components/challenge-detail/Header/style.scss

https://topcoder.atlassian.net/browse/TSJR-332

Remove differentiation for special tags

---

.circleci/config.yml
src/shared/components/GUIKit/DropdownSkills/index.jsx
src/shared/components/GUIKit/DropdownSkills/style.scss

https://github.com/topcoder-platform/community-app/issues/6932

Add drop shadow to skill selector on gig appliction

---

src/server/index.js

https://topcoder.atlassian.net/browse/PROD-4429

PROD-4429 More CSP headers

---

src/shared/components/SubmissionPage/Submit/index.jsx
src/shared/components/SubmissionPage/Submit/styles.scss
src/shared/components/challenge-detail/Specification/SideBar/index.jsx
src/shared/components/challenge-detail/Specification/index.jsx

https://topcoder.atlassian.net/browse/PROD-4430

Topgear updates to challenge details and submission pages PROD-4430

---

src/shared/containers/Dashboard/index.jsx

https://topcoder.atlassian.net/browse/CORE-346

CORE-346 remove gigs feed from home

---

__tests__/shared/components/ProfilePage/BadgesModal/__snapshots__/index.jsx.snap
__tests__/shared/components/ProfilePage/Stats/SubTrackChallengeView/GalleryModal/__snapshots__/index.jsx.snap
__tests__/shared/components/tc-communities/__snapshots__/JoinCommunity.jsx.snap
config/webpack/development.js
config/webpack/production.js
config/webpack/qa.js
package-lock.json
package.json

https://topcoder.atlassian.net/browse/PROD-4372

PROD DEPLOY - PROD-4372

---

src/shared/components/challenge-detail/Submissions/index.jsx

HOTFIX - submissions tab crashing on latest IC5.  As far as I can tell, this is the first time we've hit this particular code, due to how we've set up this IC.

Fix for PS-261

---

src/shared/components/challenge-detail/Specification/styles.scss

Added some additional styling for the link that points to a Topcoder Phoenix work item.

TOP-1512 - Link to Phoenix Styles

---

src/shared/containers/Dashboard/ChallengesFeed.jsx

https://topcoder.atlassian.net/browse/TOP-1579

TOP-1579 update config of challengesFeed on dashboard -> dev

---

src/shared/components/challenge-listing/Listing/Bucket/index.jsx
src/shared/components/challenge-listing/Listing/index.jsx

Show all past challenges to admins, regardless of registration or participation

---

src/shared/utils/url.js

https://topcoder.atlassian.net/browse/CORE-566 - Change activity feed to "Opportunities"

CORE-566 - Rename activity feed to Opportunities

---

src/shared/components/challenge-detail/Submissions/index.jsx

https://topcoder.atlassian.net/browse/PS-295?focusedCommentId=81047

PROD - Add additional check for ICs that run that don't have the data dashboard

---

__tests__/shared/components/challenge-listing/Listing/__snapshots__/Bucket.jsx.snap

https://topcoder.atlassian.net/browse/PM-337

PROD release of 337

---

src/shared/utils/url.js

- Explicitly check for url and then allow redirect

PM-196: xss dom security issue

---

Dockerfile
automated-smoke-test/Dockerfile

- Created and gave custom user the permission in docker to avoid default user privilege error.

PM-200: default user privilege

---

automated-smoke-test/config/automation-config-dev.json
automated-smoke-test/config/automation-config-local.json
automated-smoke-test/config/automation-config-prod.json
automated-smoke-test/test-data/test-data.json

- Removed hardcoded passwords from test config files

PM-207: removed hardcoded passwords

---

config/default.js
src/shared/components/challenge-detail/Specification/index.jsx

https://topcoder.atlassian.net/browse/PM-160
Updated links

PM-160 Update design challenge links

---

src/server/index.js

- Somehow, forgot to add this route in my previous PR.

PM-594: added feeds route

---

.circleci/config.yml
Dockerfile

- Updated node version in dockerfile

fix: updated node version in dockerfile

---

package-lock.json
src/shared/app.jsx
src/shared/services/recruitCRM.js

https://topcoder.atlassian.net/browse/PM-698

fix: pm-698

---

src/shared/containers/tc-communities/tco20/Header.jsx
src/shared/utils/url.js

- Added a check to encode uri component for return url to avoid xss dom attack

fix(PM-714): encode uri return url to fix xss dom error

---

src/shared/components/Contentful/MemberTalkCloud/MemberTalkCloud.jsx

- Removed math.random to fix security issue.

fix(PM-717): remove Math.random() usage

---

src/shared/components/SubmissionManagement/DownloadArtifactsModal/index.jsx
src/shared/components/SubmissionManagement/DownloadArtifactsModal/style.scss
src/shared/components/SubmissionManagement/RatingsListModal/index.jsx
src/shared/components/SubmissionManagement/RatingsListModal/styles.scss
src/shared/components/challenge-detail/MySubmissions/SubmissionsList/index.jsx
src/shared/components/challenge-detail/MySubmissions/SubmissionsList/styles.scss
src/shared/components/challenge-detail/MySubmissions/index.jsx
src/shared/containers/challenge-detail/index.jsx
src/shared/utils/files.js

- Added the button in the submission list of my submissions tab
- Added corresponding modal in the container
- Updated the modal styles to match the existing modal style

feat(PM-811): Show download artifacts modal in my submissions tab

---

src/shared/components/SubmissionManagement/DownloadArtifactsModal/index.jsx

- Fixed download artifacts in my submissions

fix(PM-896): download artifacts in my submissions

---

src/shared/containers/SubmissionManagement/index.jsx

- Fixed download artifacts in submission management screen

fix(PM-896): submission artifact download in submission management screen

---

src/shared/components/SubmissionPage/FilestackFilePicker/index.jsx

make sure sharepoint urls have a path as well

PM-967 - make sure sharepoint urls have a path as well

---

config/default.js

https://topcoder.atlassian.net/browse/PM-967 - tg has reported another allowed domain for submission

PM-967 - add more tg domanis for submission

---

.circleci/config.yml
src/shared/components/challenge-listing/ChallengeTab/index.jsx
src/shared/containers/Dashboard/index.jsx

- Removed innovation challenges tab
Ticket link - https://topcoder.atlassian.net/browse/PM-1346

fix(PM-1346): Removed innovation challenges tab

---

src/shared/components/challenge-listing/CopilotOpportunityCard/index.jsx
src/shared/components/challenge-listing/CopilotOpportunityCard/style.scss

fixes the title and adds new colour for cancelled status
fixes #1517

fix: copilot opportunity title and color for canceled opportunities
