src/shared/actions/challenge-listing.js
src/shared/components/challenge-listing/index.jsx
src/shared/containers/ChallengeListing/index.jsx
src/shared/reducers/challenge-listing.js
src/shared/reducers/index.js
src/shared/services/challenges.js
src/shared/utils/tc.js

- Initial loading of challenges into the listing is done with Redux
actions / reducers / state;
- My challenges are fetched again.
- If navigation around the listing page triggers loading of additional
challenges, it is not handled properly (old fetch code is executed,
which can be kind of fine for the stand-alone listing, but definitely
not good for the listing inside TC communities).
- Challenge counts in the sidebar are wrong.
- In general there is a lot of room for further improvements.

WIP: Challenge listing refactoring

---

__tests__/shared/actions/challenge-listing/index.js
__tests__/shared/components/challenge-listing/Filters/FiltersPanel.jsx
__tests__/shared/reducers/challenge-listing/index.js
src/shared/actions/challenge-listing/index.js
src/shared/components/challenge-detail/Header/ChallengeTags.jsx
src/shared/components/challenge-detail/Header/index.jsx
src/shared/components/challenge-listing/Filters/FiltersPanel/index.jsx
src/shared/containers/challenge-detail/index.jsx
src/shared/containers/challenge-listing/Listing/index.jsx
src/shared/reducers/challenge-listing/index.js
src/shared/services/challenges.js
src/shared/utils/challenge-listing/filter.js

fix issue #200

---

src/shared/components/challenge-listing/index.jsx
src/shared/reducers/challenge-listing/index.js
src/shared/routes/Topcoder/ChallengeListing.jsx
src/shared/utils/url.js

The fix will check the startDate and endDate, if date is invalid, then ignore them in the search logic.

Fix issue #212

---

src/shared/components/challenge-detail/Header/TabSelector/index.jsx

issue294 -iversonLv- Submission count is not displayed in the tab

---

src/shared/components/challenge-detail/Winners/index.jsx

fixed #257 corrected download link for design submission download

fixed #257 corrected download link for design submission download

---

src/shared/utils/challenge-listing/buckets.js
src/shared/utils/challenge-listing/filter.js
src/shared/utils/challenge-listing/sort.js

https://github.com/topcoder-platform/community-app/issues/282

Issue 282: Fixed challenge listing sorting by next submission or checkpoint date

---

src/shared/components/LeaderboardAvatar/index.jsx
src/shared/components/challenge-listing/ChallengeCard/Status/index.jsx

fixed #366 passing domain for user profiles avatar

fixed #366 passing domain for user profiles avatar

---

src/shared/actions/topcoder_header.js
src/shared/components/TopcoderFooter/style.scss
src/shared/components/TopcoderHeader/desktop/SubMenu/Item/index.jsx
src/shared/components/TopcoderHeader/desktop/SubMenu/index.jsx
src/shared/components/TopcoderHeader/index.jsx
src/shared/components/TopcoderHeader/mobile/Header/style.scss
src/shared/components/TopcoderHeader/style.scss
src/shared/components/challenge-listing/Filters/ChallengeSearchBar/style.scss
src/shared/reducers/topcoder_header.js

#339 rely on #337 be fixed, so I rise PR for them together

Fix issue #337, #339, #223

---

src/shared/components/Avatar/index.jsx
src/shared/components/challenge-listing/Tooltips/UserAvatarTooltip/index.jsx
src/shared/components/challenge-listing/Tooltips/UserAvatarTooltip/style.scss

Fix issue #287

---

src/shared/actions/challenge.js
src/shared/services/challenges.js

Fixes #479 
I made sure that unregistering from a challenge works but when I was trying to test registering a challenge, I keep getting a `Invalid URL http://localhost:3000/challenges/30051410/?type=develop` error. Not sure what's wrong with that.

Use api v3 for challenge register and unregister #479

---

src/shared/components/Settings/Account/MyAccount/EmailVerifiResult/Failed/index.jsx

Fix for Issue #1155   
Fixing the page error ("assets is not a function") upon choosing "I Disagree" link on received verification email after changing email in profile setting.
Email Verification Failed page is now shown correctly.

Fix for Profile Settings - email change verification issue

---

src/shared/components/ProfilePage/StatsCategory/index.jsx

fix issue #1003
Chrome –members –Idea Generation “0 wins” is not getting displayed in summary view

fix issue #1003

---

src/shared/components/ProfilePage/Header/index.jsx

fix issue #1010
broken profile image is shown for some member

fix issue #1010

---

src/shared/containers/Profile.jsx

Issue #980: Member profile: Order of icons under profile photo should be the same as the Track and subtracks list

---

src/shared/components/challenge-detail/Specification/SideBar/index.jsx

Challenge details page sidebar had the link ‘here’ without proper spacing in the paragraph

Fix side bar `here` link spacing

---

src/shared/components/ProfilePage/Stats/ChartTooltip/index.jsx
src/shared/components/ProfilePage/Stats/HistoryGraph/index.jsx

As we are sending absolute url now, so we don't need `<Link>` component any more.

fix the link

---

src/shared/components/Settings/Account/MyAccount/index.jsx

Disabled Verification button when email is empty

Disabled Verification btn

---

src/shared/components/Settings/Tools/Devices/index.jsx
src/shared/components/Settings/Tools/ServiceProviders/index.jsx
src/shared/components/Settings/Tools/Software/index.jsx
src/shared/components/Settings/Tools/Subscriptions/index.jsx
src/shared/containers/Settings.jsx

Show success message on save

---

__tests__/shared/components/ProfilePage/__snapshots__/index.jsx.snap
src/shared/components/ProfilePage/index.jsx
src/shared/containers/Profile.jsx

@ThomasKranitsas please check it

The country value of Profile page get from lookup data

---

.circleci/config.yml
package-lock.json
package.json
src/shared/components/Contentful/Banner/themes/tco19.scss
src/shared/components/Contentful/ContentBlock/themes/TCO19.scss
src/shared/components/Looker/index.jsx
src/shared/components/ProfilePage/index.jsx
src/shared/components/Settings/Account/MyAccount/index.jsx
src/shared/components/Settings/Preferences/Email/index.jsx
src/shared/components/Settings/Profile/BasicInfo/index.jsx
src/shared/components/Settings/Profile/Hobby/index.jsx
src/shared/components/Settings/Profile/Hobby/styles.scss
src/shared/components/Settings/Profile/Skills/index.jsx
src/shared/components/Settings/Profile/Skills/styles.scss
src/shared/components/tc-communities/Header/index.jsx
src/shared/routes/Communities/TCO03/Routes.jsx
src/shared/routes/Communities/TCO07/Routes.jsx
src/shared/routes/Topcoder/Routes.jsx

Reverts topcoder-platform/community-app#2356
Causing production break

Revert "develop"

---

src/shared/components/Settings/Profile/Education/index.jsx
src/shared/components/Settings/Profile/Education/styles.scss
src/shared/components/Settings/Profile/Work/index.jsx
src/shared/components/Settings/Profile/Work/styles.scss
src/shared/reducers/page/ui/settings.js

@sushilshinde Sorry for the delay, here we go.

PR with changes from F2F for Language / Work and Education

---

src/shared/components/Settings/Profile/Education/List/Item/index.jsx
src/shared/components/Settings/Profile/Education/index.jsx
src/shared/components/Settings/Profile/Hobby/index.jsx
src/shared/components/Settings/Profile/Language/index.jsx
src/shared/components/Settings/Profile/Skills/index.jsx
src/shared/components/Settings/Profile/Work/List/Item/index.jsx
src/shared/components/Settings/Profile/Work/List/Item/styles.scss
src/shared/components/Settings/Profile/Work/index.jsx
src/shared/components/Settings/Profile/Work/styles.scss
src/shared/components/Settings/Tools/Devices/index.jsx
src/shared/components/Settings/Tools/ServiceProviders/index.jsx
src/shared/components/Settings/Tools/Software/index.jsx
src/shared/components/Settings/Tools/Subscriptions/index.jsx

Fix issues of Topcoder Member Profile UI Fixes and Enhancements - Part 2

---

__tests__/shared/components/Header/__snapshots__/index.jsx.snap
src/shared/components/Header/index.jsx

Pass openMore shared variable between TopNav and LoginNav

Fix for issues#2519

---

src/shared/components/Settings/Profile/Education/index.jsx
src/shared/components/Settings/Profile/Hobby/index.jsx
src/shared/components/Settings/Profile/Language/index.jsx
src/shared/components/Settings/Profile/Skills/index.jsx
src/shared/components/Settings/Profile/Work/index.jsx
src/shared/components/Settings/Tools/Devices/index.jsx
src/shared/components/Settings/Tools/ServiceProviders/index.jsx
src/shared/components/Settings/Tools/Software/index.jsx
src/shared/components/Settings/Tools/Subscriptions/index.jsx
src/shared/utils/settings.js

- Update validateDates logic as backend and create common function for validation
- Update invalid message after clicks submit
- Show error message when language is duplicate
@gurmeetb Please review it

Fix issues of profile enhancements Part 2

---

src/shared/components/challenge-detail/Header/index.jsx
src/shared/containers/challenge-detail/index.jsx

#2910 
Hide contest title from screen reader when menu is opened.

Fix for Issue #2910 - Don't read out title when menu open

---

src/shared/components/challenge-listing/Filters/FiltersCardsType/style.scss

issue 2743 fix

---

src/assets/images/tco19_logo_black.svg

https://github.com/topcoder-platform/community-app/issues/2830

Topcoder open logo add title and aria-label.

---

src/shared/components/challenge-listing/ChallengeCard/Prize/Tip/Bonus/index.jsx
src/shared/components/challenge-listing/ChallengeCard/Prize/Tip/Prize/index.jsx

#2889   
MSFT-231 Fix prize and bonus being read out incorrectly by screen reader (NVDA).

Fix for Issue #2889 Challenge listing prize read out

---

.circleci/config.yml
__tests__/shared/utils/__snapshots__/markdown.js.snap
package-lock.json
package.json
src/server/index.js
src/shared/components/Contentful/Article/themes/default.scss
src/shared/components/Looker/index.jsx
src/shared/containers/tc-communities/Loader.jsx
src/shared/utils/markdown.js

Feature contentful development

---

src/shared/utils/memberStats.js

Reverts topcoder-platform/community-app#3578 because it is origin of https://github.com/topcoder-platform/community-app/issues/3586

Revert "issue 3394 fix"

---

src/shared/components/ProfilePage/Stats/index.jsx
src/shared/components/ProfilePage/index.jsx
src/shared/containers/ProfileStats.jsx

#3590   
Fix blank page issue when using back arrow from directly accessed rating page

Fix for Issue #3590 Blank page after back arrow rating page

---

__tests__/shared/components/Leaderboard/__snapshots__/Podium.jsx.snap
src/shared/components/Leaderboard/PodiumSpot/index.jsx

#3978   
Set up default value of themeName property in PodiumSpot component to fix the issue of Leaderboard table page goes blank.

Fix for Issue #3978 Leaderboard page goes blank

---

package-lock.json
package.json

Add postinstall script to remove nested topcoder-react-utils dependency from navigation-component and topcoder-react-ui-kit.
#4093 
The issue is caused by the version of topcoder-react-utils component being used by navigation-component (0.7.9) and topcoder-react-ui-kit (^0.7.8) is higher than the one used by community-app (0.7.8)
https://github.com/topcoder-platform/topcoder-react-ui-kit/blob/dc6ce000568412665ab98e1a08980c24a0d8e4a1/package.json#L41  
https://github.com/topcoder-platform/navigation-component/blob/cbe727f4eea63b1bc992ba03c5f93f932d905de1/package.json#L68  
For a quick solution, we can manually delete nested topcoder-react-utils folder inside the nested node_modules of those two components.
I've added postinstall command to remove those nested dependency.
It will be …

Issue #4093 - Dev mode issue

---

.circleci/config.yml
src/shared/components/tc-communities/AccessDenied/index.jsx
src/shared/containers/SubmissionPage.jsx

https://github.com/topcoder-platform/community-app/issues/4144

Fix submit blank issue

---

__tests__/shared/components/challenge-listing/Filters/__snapshots__/ChallengeFilters.jsx.snap
__tests__/shared/components/challenge-listing/Filters/__snapshots__/ChallengeSearchBar.jsx.snap
src/shared/components/challenge-listing/Filters/ChallengeFilters.jsx
src/shared/components/challenge-listing/Filters/ChallengeSearchBar/index.jsx
src/shared/components/challenge-listing/Filters/ChallengeSearchBar/style.scss

I added X button to clear the challenge search as described in this issue: https://github.com/topcoder-platform/community-app/issues/3622.

Add X button to clear the challenge search.

---

src/shared/utils/memberStats.js

Fix issue 4291, add subTrack 'DEVELOP_MARATHON_MATCH' to valid 'DEVELOP' tracks.

Fix issue 4291, add subTrack 'DEVELOP_MARATHON_MATCH' to valid 'DEVELOP' tracks.

---

.circleci/config.yml
__tests__/shared/components/Header/__snapshots__/index.jsx.snap
config/default.js
config/production.js
package.json
src/shared/actions/index.js
src/shared/actions/tracking.js
src/shared/components/Header/index.jsx
src/shared/components/Notifications/index.jsx

#4309: Move tracking from topcoder-react-lib to community-app

---

src/shared/components/ProfilePage/Stats/HistoryGraph/index.jsx
src/shared/components/challenge-detail/RecommendedActiveChallenges/ChallengesCard/index.jsx
src/shared/components/challenge-listing/ChallengeCard/index.jsx

https://github.com/topcoder-platform/community-app/issues/4379

Fix MM challenge links

---

__tests__/shared/components/Dashboard/SRM/__snapshots__/index.jsx.snap
src/shared/components/Dashboard/CurrentActivity/Challenges/index.jsx
src/shared/components/Dashboard/CurrentActivity/Challenges/style.scss
src/shared/components/Dashboard/SRM/index.jsx

Remove `View Past SRMS` and `Past Challenges` links from dashboard.
Closes topcoder-platform/community-app#4470

refactor(dashboard): remove legacy links

---

config/default.js
src/server/index.js
src/shared/containers/SubmissionManagement/index.jsx
src/shared/containers/SubmissionPage.jsx
src/shared/containers/challenge-detail/index.jsx

Issue: https://github.com/topcoder-platform/community-app/issues/4380
Dependencies:
**topocoder-react-lib**: https://github.com/topcoder-platform/topcoder-react-lib/pull/187

Issue #4380 - Fix challenge register/unregister

---

src/shared/components/challenge-detail/Registrants/index.jsx

Issue: https://github.com/topcoder-platform/community-app/issues/4537
Dependency: https://github.com/topcoder-platform/topcoder-react-lib/pull/195

Issue #4537 : Challenge Details - Registrants data bind

---

src/shared/actions/challenge-listing/index.js
src/shared/components/challenge-listing/Listing/index.jsx
src/shared/containers/challenge-listing/Listing/index.jsx

Issue: https://github.com/topcoder-platform/community-app/issues/4393
Dependency: https://github.com/topcoder-platform/topcoder-react-lib/pull/194

Issue#4393 - Challenge Listings: Challenges not loading for subcommunitie

---

src/shared/actions/terms.js
src/shared/components/ReviewOpportunityDetailsPage/Sidebar/index.jsx
src/shared/components/Terms/index.jsx
src/shared/components/challenge-detail/Specification/SideBar/index.jsx
src/shared/containers/Terms.jsx
src/shared/containers/challenge-detail/index.jsx
src/shared/containers/terms-detail/index.jsx
src/shared/reducers/terms.js

Issue: https://github.com/topcoder-platform/community-app/issues/4562
Dependency: https://github.com/topcoder-platform/topcoder-react-lib/pull/203

Issue#4562 : Updated terms to use V5 API

---

src/shared/components/challenge-detail/Header/TabSelector/index.jsx
src/shared/components/challenge-detail/Header/index.jsx
src/shared/components/challenge-detail/MySubmissions/SubmissionsList/index.jsx
src/shared/components/challenge-detail/MySubmissions/index.jsx
src/shared/components/challenge-detail/Submissions/SubmissionRow/SubmissionHistoryRow/index.jsx
src/shared/components/challenge-detail/Submissions/SubmissionRow/index.jsx
src/shared/containers/challenge-detail/index.jsx
src/shared/utils/challenge.js

Issue: https://github.com/topcoder-platform/community-app/issues/4583

Issue#4583 : Fix mySubmissions of MM challenges

---

.circleci/config.yml
__tests__/shared/components/Header/__snapshots__/index.jsx.snap
__tests__/shared/components/__snapshots__/TopcoderFooter.jsx.snap
config/default.js
config/production.js
src/shared/components/TopcoderFooter/index.jsx
src/shared/components/buttons/themed/tc.scss

Feature contentful

---

src/shared/actions/tc-communities/index.js

Issue: https://github.com/topcoder-platform/community-app/issues/4650
Dependency: https://github.com/topcoder-platform/topcoder-react-lib/pull/211

Fix Issue#4650 : Pass old groups ids to filter

---

package-lock.json
src/shared/utils/challenge-listing/sort.js

Fix/rewrite TIME_TO_REGISTER and TIME_TO_SUBMIT sorting functions.
Addresses topcoder-platform/community-app#4715

fix(challenge-listing): sorting functions

---

__tests__/shared/components/challenge-listing/Filters/__snapshots__/FiltersPanel.jsx.snap
src/shared/components/challenge-listing/Filters/FiltersPanel/index.jsx
src/shared/components/challenge-listing/Filters/FiltersPanel/style.scss
src/shared/components/challenge-listing/Listing/ReviewOpportunityBucket/index.jsx
src/shared/components/challenge-listing/ReviewOpportunityCard/index.jsx

Issue: https://github.com/topcoder-platform/community-app/issues/4718
Dependency: https://github.com/topcoder-platform/topcoder-react-lib/pull/218

Issue#4718 : Open for review bucket : Impact of Track/Subtrack updates

---

src/shared/components/tc-communities/Header/index.jsx

Issue: https://github.com/topcoder-platform/community-app/issues/4783

updated isZurichCompetitor to use group 'oldId' instead 'id'

---

src/shared/components/challenge-listing/ChallengeCard/Status/index.jsx
src/shared/components/challenge-listing/Tooltips/ProgressBarTooltip/index.jsx
src/shared/utils/challenge-detail/helper.jsx
src/shared/utils/challenge-listing/helper.js
src/shared/utils/challenge-listing/sort.js

* Add `phaseStartDate` and `phaseEndDate` helper functions at `challenge-detail/helper`
to get the correct start/end date of a phase.
* `TIME_TO_REGISTER`, `TIME_TO_SUBMIT` and `MOST_RECENT` sorting functions updated to reflect above change.
* `ProgressBarTooltip` and `ChallengeCard/Status` updated to display correct phase start/end dates.
Addresses topcoder-platform/community-app#4715, topcoder-platform/community-app#4716

fix(challenge-listing): sorting by dates & phase displaying

---

__tests__/shared/components/challenge-listing/__snapshots__/index.jsx.snap
src/shared/actions/challenge-listing/index.js
src/shared/components/challenge-listing/Listing/index.jsx
src/shared/components/challenge-listing/index.jsx
src/shared/containers/challenge-listing/Listing/index.jsx
src/shared/containers/challenge-listing/Sidebar.jsx
src/shared/utils/challenge-listing/buckets.js
src/shared/utils/challenge-listing/helper.js

Drop out the old `resource-api` call to get user challenges.
Use `GET /challenges?memberId=<userId>&status=Active` instead.
Add `challenge.users[userId]` property for user challenges.
Remove `userChallenges` array from filter, use `challenge.users[userId]` instead.
Addresses topcoder-platform/community-app#4782

fix(challenge-listing): my challenges bucket/filter

---

src/shared/components/ReviewOpportunityDetailsPage/ChallengeSpecTab/index.jsx
src/shared/components/challenge-detail/Specification/index.jsx

Remove unnecessary `finalSubmissionGuidelines` (it's no longer in use) usages from
`challenge-detail/Specification` and `ReviewOpportunityDetailsPage/ChallengeSpecTab` components.

refactor(challenge-detail): remove `finalSubmissionGuidelines` usages

---

src/shared/actions/challenge-listing/index.js
src/shared/components/challenge-detail/Header/DeadlinesPanel/index.jsx
src/shared/components/challenge-detail/Header/index.jsx
src/shared/utils/challenge-listing/helper.js

Issues: https://github.com/topcoder-platform/community-app/issues/4782 https://github.com/topcoder-platform/community-app/issues/4723

Milestone v1.2 part3

---

src/shared/containers/challenge-detail/index.jsx

Fix a typo in if condition used to show thrive articles.
- It was showing them only for the Design track.
- Articles will be shown for all tracks except for the Design track.
References #4765

fix(challenge-detail): condition for showing thrive articles 

---

src/shared/components/SubmissionManagement/SubmissionManagement/index.jsx

fix(submission-management): missing `Add Submission` button

---

src/shared/components/ProfilePage/Stats/HistoryGraph/index.jsx

Fix wrong MM URLs at `ProfilePage/Stats/HistoryGraph`
- Old (wrong) URL: `/challenges/<challengeId>`
- New (correct) URL: `${config.URL.COMMUNITY}/tc?module=MatchDetails&rd=<challengeId>`
Ref #4760

fix(profile-page): wrong MM url at history graph

---

package.json
src/shared/components/ProfilePage/Stats/SubTrackChallengeView/index.jsx

fix: for issue #2069

---

src/shared/components/ProfilePage/Stats/SubTrackChallengeView/index.jsx

Profile Stats Challenges : Fix loading icon

---

src/shared/components/challenge-listing/Tooltips/ProgressBarTooltip/index.jsx
src/shared/utils/challenge-listing/sort.js

Added !isEmpty check before call phaseStartDate and phaseEndDate

---

__tests__/shared/components/Header/__snapshots__/index.jsx.snap
src/shared/components/Header/index.jsx
src/shared/components/Header/style.scss
src/shared/components/TopcoderFooter/style.scss
src/shared/routes/Topcoder/styles.scss

#4294: Fix dropdown issue being hidden behind footer on profile settings page.

Fix for Issue #4294 Dropdown hidden behind on profile settings page

---

src/shared/containers/terms-detail/index.jsx

Issue: https://github.com/topcoder-platform/community-app/issues/4784
Dependency: https://github.com/topcoder-platform/topcoder-react-lib/pull/254

fix: for issue #4784

---

src/shared/components/challenge-listing/Listing/Bucket/index.jsx
src/shared/components/challenge-listing/Listing/index.jsx

fix(challenge-listing): do not render buckets that have 0 challenges

---

src/shared/containers/terms-detail/index.jsx

Terms: Hotfix show details before redirect

---

src/shared/components/challenge-listing/Listing/Bucket/index.jsx
src/shared/reducers/challenge-listing/index.js
src/shared/utils/challenge-listing/buckets.js
src/shared/utils/challenge-listing/sort.js

#4973 
Fix sorted of by 'Most recent' of My Challenges bucket and sorted by 'Review start date' of Open for Review bucket
to be based of challenge start date in descending order.

Fix for Issue #4973

---

.circleci/config.yml
package.json
src/shared/components/ChallengeTile/index.jsx
src/shared/components/Dashboard/CurrentActivity/Header/index.jsx
src/shared/components/SubmissionManagement/Submission/index.jsx
src/shared/reducers/page/dashboard.js
src/shared/utils/tc.js

Issues: #4926 #4948 #5004 
Dependency: https://github.com/topcoder-platform/topcoder-react-lib/pull/263

Smoke Testing 2020-10-01

---

__tests__/shared/components/challenge-listing/Listing/__snapshots__/Bucket.jsx.snap
__tests__/shared/components/challenge-listing/Sidebar/__snapshots__/index.jsx.snap
__tests__/shared/components/challenge-listing/__snapshots__/index.jsx.snap
src/shared/actions/challenge-listing/sidebar.js
src/shared/components/challenge-listing/Listing/Bucket/index.jsx
src/shared/components/challenge-listing/Listing/index.jsx
src/shared/components/challenge-listing/Sidebar/BucketSelector/index.jsx
src/shared/components/challenge-listing/Sidebar/index.jsx
src/shared/components/challenge-listing/index.jsx
src/shared/containers/challenge-listing/Listing/index.jsx
src/shared/reducers/challenge-listing/sidebar.js

Displaying more challenges without changing URL or sidebar filter.

Fix for Issue #5002 - Stays on main challenge listing when view more challenges is clicked.

---

src/shared/components/challenge-listing/Filters/ChallengeFilters.jsx
src/shared/components/challenge-listing/Filters/FiltersPanel/index.jsx
src/shared/reducers/challenge-listing/index.js
src/shared/utils/challenge-listing/buckets.js

* The date filters at challenge listing page was using
`startDateStart` (start date) and `endDateEnd` (end date)
query parameters for `GET /challenges` call.
* It now uses `startDateEnd` (end date) and `endDateStart` (start date)
instead, in  compliance with previous implementation.
Addresses #4984

fix(challenge-listing): date filters will use correct query params

---

src/shared/components/challenge-detail/Header/ChallengeTags.jsx
src/shared/components/challenge-listing/Filters/ChallengeFilters.jsx
src/shared/containers/challenge-listing/FilterPanel.jsx
src/shared/reducers/challenge-listing/index.js
src/shared/reducers/challenge-listing/sidebar.js
src/shared/utils/url.js

Challenge: https://www.topcoder.com/challenges/5bc4b0ac-aa74-4ac1-9c7d-db4f192c87e3
Submission: 405645

f2f filterfix

---

__tests__/shared/components/__snapshots__/TopcoderFooter.jsx.snap
src/shared/components/TopcoderFooter/index.jsx

issue 5035 fix

---

config/default.js
config/production.js
src/shared/components/tc-communities/Header/index.jsx
src/shared/routes/Communities/TCO19/Routes.jsx
src/shared/routes/Communities/Wipro/Routes.jsx

Fix logout to Wipro and TCO19

---

src/shared/components/TopcoderFooter/index.jsx

Footer - Hide Join Community if user logged in

---

config/default.js
config/production.js
src/shared/components/tc-communities/Header/index.jsx
src/shared/routes/Communities/Blockchain/Routes.jsx
src/shared/routes/Communities/CS/Routes.jsx
src/shared/routes/Communities/Cognitive/Routes.jsx
src/shared/routes/Communities/Comcast/Routes.jsx

Fix Logout retUrl to all sub-communities

---

src/shared/components/ProfilePage/Stats/SubTrackChallengeView/index.jsx
src/shared/utils/tc.js

Issue: https://github.com/topcoder-platform/community-app/issues/4527
Challenge: https://www.topcoder.com/challenges/d755a633-8564-4637-813f-e6987b016435

refactor: use v4 api for member stats history

---

src/shared/components/challenge-listing/Filters/FiltersPanel/index.jsx

fix: reset review opportunity filter

---

src/shared/components/Settings/Account/MyAccount/index.jsx

Hide Challenge Email

---

.circleci/config.yml
package.json

Smoke Testing 2020/11/10 - TCX issues

---

.circleci/config.yml
src/shared/containers/ContentfulLoader.jsx

Media queries fix

---

src/shared/components/challenge-detail/Header/TabSelector/index.jsx
src/shared/components/challenge-detail/Specification/SideBar/index.jsx
src/shared/components/challenge-detail/Specification/index.jsx

Issue #5041
Hide forum tab if haven't a forumId or discussions

Hotfix 2 - Smoke Testing 2020/11/12 - New forums 

---

package.json
src/shared/components/challenge-detail/Header/index.jsx
src/shared/containers/challenge-detail/index.jsx
src/shared/utils/challenge-detail/helper.jsx

Fix prizeSets logical to get 'placements' instead first one

---

.circleci/config.yml
src/shared/components/GUIKit/DropdownTerms/index.jsx
src/shared/containers/Gigs/RecruitCRMJobApply.jsx

Gig apply fixes

---

__tests__/shared/components/challenge-listing/__snapshots__/index.jsx.snap
__tests__/shared/components/challenge-listing/index.jsx
__tests__/shared/reducers/challenge-listing/sidebar.js
src/shared/actions/challenge-listing/sidebar.js
src/shared/components/DateRangePicker/index.jsx
src/shared/components/DateRangePicker/style.scss
src/shared/components/challenge-detail/Header/ChallengeTags.jsx
src/shared/components/challenge-listing/Filters/FiltersPanel/index.jsx
src/shared/components/challenge-listing/Filters/FiltersPanel/style.scss
src/shared/components/challenge-listing/Listing/Bucket/index.jsx
src/shared/components/challenge-listing/Listing/ReviewOpportunityBucket/index.jsx
src/shared/components/challenge-listing/Listing/index.jsx
src/shared/components/challenge-listing/Sidebar/index.jsx
src/shared/components/challenge-listing/index.jsx
src/shared/containers/challenge-detail/index.jsx
src/shared/containers/challenge-listing/FilterPanel.jsx
src/shared/containers/challenge-listing/Listing/index.jsx
src/shared/containers/challenge-listing/Sidebar.jsx
src/shared/reducers/challenge-listing/index.js
src/shared/reducers/challenge-listing/sidebar.js
src/shared/utils/challenge-listing/buckets.js

**issuecomment-741596441**:  _(1) intentional_, _(2) fixed_: layout issue, _(3) fixed_: after coming back from the challenge details, the default tab is 'Active' and default bucket is 'Open for registration'
**issuecomment-741600474**: _fixed_: layout issue
**issuecomment-741904592**: _fixed_: forgot to set the challenge 'types' filter to all when clicking on the challenge Tags
&nbsp;
About 741904592:  `search=<tag>` vs `tags[]=<tag>`
- There are modules of the community-app allowing to search by multiple tags (ex: Contentful EDU search) while `search=<tag>`  is allowing searching by a single tag only
- `search=<tag>` searching in challenges' name, description and tags, so there is a confused case that a challenge with only HTML tag but its description including the keyword 'Java' still …

Filter update -- fix issue 5068's comments

---

.circleci/config.yml
__tests__/shared/components/Settings/Preferences/Email/__snapshots__/index.jsx.snap
package-lock.json
src/server/routes/mailchimp.js
src/server/services/mailchimp.js
src/shared/actions/newsletterPreferences.js
src/shared/components/NewsletterSignupForMembers/ConfirmModal/style.scss
src/shared/components/Settings/Preferences/Email/index.jsx
src/shared/components/Settings/Preferences/Email/styles.scss
src/shared/components/Settings/ToggleableItem/index.jsx
src/shared/containers/EmailSubscribeForm/index.jsx
src/shared/containers/NewsletterPreferences.jsx
src/shared/containers/NewsletterSignupForMembers.jsx
src/shared/reducers/newsletterPreferences.js

Email pref revamp develop

---

.circleci/config.yml
src/shared/components/Contentful/Route.jsx
src/shared/routes/index.jsx

Route redirects

---

.circleci/config.yml
config/default.js
package.json
src/shared/components/Settings/Preferences/index.jsx
src/shared/components/challenge-detail/Specification/SideBar/index.jsx
src/shared/components/challenge-detail/Winners/Winner/index.jsx

https://github.com/topcoder-platform/community-app/issues/5433
https://github.com/topcoder-platform/community-app/issues/5329
https://github.com/topcoder-platform/community-app/issues/5248

Smoke Testing 2021/01/26 - Bug Bash

---

.circleci/config.yml
src/shared/components/GUIKit/JobListCard/index.jsx
src/shared/components/GUIKit/JobListCard/style.scss
src/shared/components/Gigs/GigApply/index.jsx

Gig mkt ab

---

.circleci/config.yml
src/shared/components/Gigs/GigDetails/style.scss

Gig details UI fixes

---

.circleci/config.yml
src/shared/components/Contentful/TracksFilter/TracksFilter.jsx

Thrive authors update

---

.circleci/config.yml

Fix circleci deployment

---

.circleci/config.yml
src/server/tc-communities/wipro/metadata.json
src/shared/containers/tc-communities/Loader.jsx
src/shared/routes/Communities/Wipro/Routes.jsx

Topgear Redirect

---

.circleci/config.yml
automated-smoke-test/config/automation-config-beta.json
automated-smoke-test/config/automation-config-dev.json
automated-smoke-test/config/automation-config-local.json
automated-smoke-test/config/automation-config-prod.json
automated-smoke-test/config/automation-config-qa.json
automated-smoke-test/config/automation-config-staging.json
automated-smoke-test/config/automation-config-test.json
automated-smoke-test/page-objects/pages/topcoder/challenge-listing/challenge-listing.helper.ts
automated-smoke-test/utils/config-helper.ts

Automated Smoke Testing - Fix search

---

.circleci/config.yml
src/assets/images/tc-edu/icon-radio-checked.svg
src/assets/images/tc-edu/icon-radio-un-check.svg
src/shared/components/Contentful/SearchBar/SearchBar.jsx
src/shared/components/Contentful/SearchPageFilter/FilterAuthor/index.jsx
src/shared/components/Contentful/SearchPageFilter/FilterAuthor/themes/default.scss
src/shared/components/Contentful/SearchPageFilter/FilterRadio/themes/default.scss
src/shared/components/Contentful/SearchPageFilter/FilterTags/index.jsx
src/shared/components/Contentful/TracksFilter/TracksTags/index.jsx

@kkartunov
Fix #5534
9bfc310
@kkartunov
Fix #5538
90cb328
@kkartunov
Fix #5541
edcf53b
@kkartunov
Fix #5542
5e8d078
@kkartunov
Fix #5543

Thrive bug fixes2

---

.circleci/config.yml
src/shared/containers/tc-communities/Loader.jsx

Topgear login redirect

---

.circleci/config.yml
automated-smoke-test/page-objects/pages/topcoder/challenge-listing/challenge-listing.helper.ts

Ast challenge listing fix

---

src/shared/components/Settings/Profile/BasicInfo/index.jsx

#5501 
use homeCountryCode or competitionCountryCode as displayed country in member settings page when country is not found in the basic_info traits

issue #5501 fix: member country is not displayed in settings

---

.circleci/config.yml
src/shared/components/Contentful/Tabs/Tabs.jsx
src/shared/components/Contentful/Tabs/index.jsx
src/shared/components/Contentful/Tabs/themes/underline-box.scss
src/shared/components/Gigs/GigApply/style.scss

New tabs theme

---

.circleci/config.yml
automated-smoke-test/conf.ts
automated-smoke-test/smoketest.sh

Issue: https://github.com/topcoder-platform/community-app/issues/5628

Automated Smoke Testing - Fix store_artifacts

---

src/shared/components/Contentful/Article/Article.jsx
src/shared/components/Contentful/Article/themes/default.scss

Thrive article page

---

automated-smoke-test/config/automation-config-beta.json
automated-smoke-test/config/automation-config-prod.json
automated-smoke-test/config/automation-config-staging.json
automated-smoke-test/page-objects/pages/topcoder/member-profile-page/member-profile.helper.ts

AST: Fix profile test data

---

.circleci/config.yml
src/shared/components/Gigs/ReferralCode/index.jsx
src/shared/reducers/growSurf.js

Gig referrals hotfix

---

.circleci/config.yml
src/server/routes/contentful.js
src/shared/components/Contentful/Article/Article.jsx
src/shared/components/Contentful/Article/themes/default.scss
src/shared/components/Gigs/LoginModal/index.jsx
src/shared/components/LoginModal/index.jsx
src/shared/components/LoginModal/modal.scss
src/shared/services/contentful.js

Thrive vulnerability 1

---

.circleci/config.yml
__tests__/shared/components/Header/__snapshots__/index.jsx.snap
config/default.js
config/production.js
src/server/services/contentful.js
src/shared/components/Contentful/Article/themes/default.scss
src/shared/components/Contentful/ArticleCard/themes/video.scss
src/shared/components/Contentful/SearchPageFilter/FilterAuthor/themes/default.scss
src/shared/containers/EDU/Search.jsx
src/shared/services/contentful.js

Issue: https://github.com/topcoder-platform/community-app/issues/5763

Thrive spooky1 p0 2

---

src/server/routes/recruitCRM.js

Adjust the RCRM related Endpoint in CA to let it be able to serve MFE (#5769)
* deploying
* ci:deploying
* redeploying
* redeploying
* reset
* reset ci

Release v1.14.0

---

src/shared/components/Gigs/GigApply/index.jsx
src/shared/components/Gigs/LoginModal/index.jsx
src/shared/components/Gigs/ReferralModal/index.jsx
src/shared/components/LoginModal/index.jsx

Reverts topcoder-platform/community-app#5804
Auth0 will set the URL to take the user to in the activation email. Login action will land the user to `retUrl` regardless of whether user comes to the "Login" tab through clicking "Login" button or through clicking "Signup" button and switching to "Login" tab.

Revert "feat: take user to /onboard in activation email"

---

.circleci/config.yml
__tests__/shared/components/Settings/Account/__snapshots__/index.jsx.snap
__tests__/shared/components/Settings/Account/index.jsx
src/shared/components/Settings/Account/LinkedAccount/AddWebLink.jsx
src/shared/components/Settings/Account/LinkedAccount/index.jsx
src/shared/components/Settings/Account/index.jsx
src/shared/components/Settings/Profile/BasicInfo/index.jsx
src/shared/components/Settings/Profile/Education/index.jsx
src/shared/components/Settings/Profile/Education/styles.scss
src/shared/components/Settings/Profile/Hobby/index.jsx
src/shared/components/Settings/Profile/Work/index.jsx
src/shared/components/Settings/Tools/Devices/index.jsx
src/shared/reducers/page/ui/settings.js

https://github.com/topcoder-platform/community-app/milestone/148

Release v1.14.3 - [Bug Bash] Fixes I (#5826)

---

.circleci/config.yml
src/shared/containers/Gigs/RecruitCRMJobDetails.jsx

Referral lock

---

.circleci/config.yml
src/shared/components/Contentful/Article/Article.jsx
src/shared/components/Contentful/Article/themes/default.scss
src/shared/components/Contentful/ArticleCard/themes/article_large.scss
src/shared/components/Contentful/SearchBar/SearchBar.jsx

Thrive spooky1 4

---

src/shared/components/Settings/Profile/Work/index.jsx
src/shared/components/Settings/Profile/Work/styles.scss
src/shared/components/challenge-listing/Filters/DatePicker.jsx

Fix Issue 5864 - Enable to Clear Date

---

.circleci/config.yml
config/default.js
config/production.js
package.json
src/server/index.js
src/server/routes/feeds.js
src/shared/actions/mmLeaderboard.js
src/shared/components/MMatchLeaderboard/index.jsx
src/shared/components/MMatchLeaderboard/style.scss
src/shared/components/MetaTags.jsx
src/shared/containers/EDU/Home.jsx
src/shared/containers/EDU/Search.jsx
src/shared/containers/EDU/Tracks.jsx

Thrive rss

---

.circleci/config.yml
src/shared/components/Contentful/Article/Article.jsx
src/shared/components/Contentful/ContentSlider/ContentSlider.jsx
src/shared/components/Contentful/ContentSlider/index.jsx
src/shared/components/Contentful/ContentSlider/themes/default.scss
src/shared/components/Contentful/Viewport/index.jsx
src/shared/components/Contentful/Viewport/themes/column.scss
src/shared/components/Contentful/Viewport/themes/grid.scss
src/shared/components/Contentful/Viewport/themes/masonry.scss

Jan fixes 2

---

src/shared/components/Settings/Account/MyAccount/index.jsx

https://github.com/topcoder-platform/community-app/issues/6283

Fix new password placeholder

---

src/shared/components/challenge-detail/Specification/index.jsx

https://github.com/topcoder-platform/community-app/issues/6289

Remove Generic Payment section from challenge details

---

src/shared/components/ProfilePage/Stats/ChartTooltip/index.jsx
src/shared/components/ProfilePage/Stats/HistoryGraph/index.jsx

fix: fix challenge link for marathon match in member statics page

fix: fix challenge link for marathon match in member statics page

---

src/shared/components/ProfilePage/Stats/ChartTooltip/index.jsx
src/shared/components/ProfilePage/Stats/HistoryGraph/index.jsx

Reverts topcoder-platform/community-app#6303

Revert "fix: fix challenge link for marathon match in member statics page"

---

.circleci/config.yml

Fix CircleCI `npm install` timeout fix.
Related with bug reported here: https://github.com/npm/cli/issues/4896

CircleCI - Timeout fix

---

__tests__/shared/components/TrackIcon/__snapshots__/index.jsx.snap
src/shared/components/TrackIcon/index.jsx
src/shared/components/TrackIcon/style.scss
src/shared/components/challenge-detail/Header/ChallengeTags.jsx
src/shared/components/challenge-detail/Header/style.scss
src/styles/_mixins/_variables.scss

Topcoder Reskin - Challenge Icons Colors

Topcoder Reskin - Challenge Icons Colors

---

.circleci/config.yml
src/shared/components/Contentful/Modal/modal-styles.scss
src/shared/components/ProfilePage/Activity/ActivityCard/index.jsx

JIRA Ticket: https://topcoder.atlassian.net/browse/PROD-1984

Reskin profile - Cherry Pick

---

src/shared/actions/challenge-listing/index.js
src/shared/components/SortingSelectBar/style.scss
src/shared/components/challenge-listing/Filters/FiltersPanel/style.scss
src/shared/utils/challenge-listing/buckets.js
src/shared/utils/challenge-listing/sort.js

https://topcoder.atlassian.net/browse/PROD-2866

Reskin challenge listing

---

.circleci/config.yml
__tests__/shared/components/Leaderboard/__snapshots__/LeaderboardTable.jsx.snap
__tests__/shared/components/Leaderboard/__snapshots__/Podium.jsx.snap
__tests__/shared/components/Leaderboard/__snapshots__/PodiumSpot.jsx.snap
src/shared/components/Leaderboard/ChallengeHistoryModal/index.jsx
src/shared/components/Leaderboard/LeaderboardTable/index.jsx
src/shared/components/Leaderboard/Podium/index.jsx
src/shared/components/Leaderboard/Podium/themes/default.scss
src/shared/components/Leaderboard/Podium/themes/tco23.scss
src/shared/components/Leaderboard/PodiumSpot/index.jsx
src/shared/components/Leaderboard/PodiumSpot/themes/styles.scss
src/shared/components/Leaderboard/PodiumSpot/themes/tco20.scss
src/shared/components/Leaderboard/PodiumSpot/themes/tco22.scss
src/shared/components/Leaderboard/PodiumSpot/themes/tco23.scss
src/shared/components/Leaderboard/avatarStyles.scss

https://topcoder.atlassian.net/browse/TCWEB-63

Tco23 leaderboards

---

.circleci/config.yml
__tests__/shared/components/challenge-listing/Listing/__snapshots__/Bucket.jsx.snap
src/shared/components/challenge-listing/Listing/Bucket/index.jsx
src/shared/components/challenge-listing/Listing/ReviewOpportunityBucket/index.jsx
src/shared/components/challenge-listing/Listing/index.jsx
src/shared/components/challenge-listing/Listing/style.scss
src/shared/components/challenge-listing/index.jsx
src/shared/containers/challenge-listing/Listing/index.jsx

Milestone: https://github.com/topcoder-platform/community-app/milestone/194 
community-app
> Issues: [TCWEB-106](https://topcoder.atlassian.net/browse/TCWEB-106) [TCA-484](https://topcoder.atlassian.net/browse/TCA-484) [PROD-2955](https://topcoder.atlassian.net/browse/PROD-2955)

Release v1.18.5

---

src/shared/containers/timeline-wall/index.jsx

fix filter nav

---

src/shared/containers/timeline-wall/modal-event-add/index.jsx
src/shared/containers/timeline-wall/modal-event-add/styles.scss

https://github.com/topcoder-platform/timeline-wall-api/issues/32

fix: update error message modal

---

__tests__/shared/components/__snapshots__/TopcoderFooter.jsx.snap
src/shared/components/TopcoderFooter/index.jsx
src/shared/containers/TopcoderHeader.jsx

https://topcoder.atlassian.net/browse/PROD-3881
Re-render uninav on sub pages & persist nav type in session storage

PROD-3881 universal nav

---

.circleci/config.yml
__tests__/shared/components/challenge-detail/Submissions/SubmissionRow/SubmissionHistoryRow/__snapshots__/index.jsx.snap
__tests__/shared/components/challenge-detail/Submissions/SubmissionRow/SubmissionHistoryRow/index.jsx
__tests__/shared/components/challenge-detail/Winners/Winner/__snapshots__/index.jsx.snap
__tests__/shared/components/challenge-detail/Winners/Winner/index.jsx
src/shared/components/challenge-detail/Submissions/SubmissionRow/SubmissionHistoryRow/index.jsx
src/shared/components/challenge-detail/Submissions/index.jsx
src/shared/components/challenge-detail/Winners/Winner/index.jsx
src/shared/components/challenge-detail/Winners/index.jsx

Hotfix for disabling download buttons

Submission download buttons

---

.circleci/config.yml
src/shared/components/Settings/Preferences/Email/index.jsx

https://topcoder.atlassian.net/browse/MKTG-1156
Updates member email preferences UI.

MKTG-1156 Email preferences update

---

config/backup-default.js
config/default.js
config/production.js
package-lock.json
package.json
src/client/index.jsx
src/shared/containers/SubmissionPage.jsx

https://topcoder.atlassian.net/browse/PROD-4399
Removes the SPRIG integration as we are about to replace it with another platform.

PROD-4399 - remove sprig integration -> develop

---

.circleci/config.yml
config/backup-default.js
config/default.js
config/production.js
src/shared/components/challenge-detail/Header/TabSelector/index.jsx

https://topcoder.atlassian.net/browse/PROD-3088

Change “Submission Review” tab to “My Submissions” instead

---

package.json
src/shared/components/challenge-detail/Registrants/index.jsx
src/shared/containers/challenge-detail/index.jsx

https://topcoder.atlassian.net/browse/PS-187

PROD - Fixes to use v5 for challenge results instead of v2

---

src/shared/components/SubmissionManagement/Submission/index.jsx
src/shared/components/SubmissionManagement/SubmissionManagement/index.jsx
src/shared/components/SubmissionManagement/SubmissionsTable/index.jsx
src/shared/components/challenge-detail/MySubmissions/SubmissionsList/index.jsx
src/shared/components/challenge-detail/MySubmissions/index.jsx
src/shared/components/challenge-detail/Registrants/index.jsx
src/shared/containers/challenge-detail/index.jsx

https://topcoder.atlassian.net/browse/TOP-655

PROD - hide download buttons on submissions for Topcrowd / Phoenix challenges

---

__tests__/shared/components/challenge-listing/Filters/__snapshots__/FiltersPanel.jsx.snap
src/shared/components/challenge-detail/Header/index.jsx
src/shared/components/challenge-detail/Specification/index.jsx
src/shared/components/challenge-detail/Specification/styles.scss
src/shared/components/challenge-listing/ChallengeCard/Status/index.jsx
src/shared/components/challenge-listing/Filters/FiltersPanel/index.jsx
src/shared/components/challenge-listing/Filters/FiltersPanel/style.scss

Production release of:
TOP-1579
TOP-1489
TOP-1550
TOP-1548
TOP-1512

Prod relese - May end

---

__tests__/shared/components/challenge-listing/Listing/__snapshots__/Bucket.jsx.snap
src/shared/components/challenge-detail/Specification/index.jsx

https://topcoder.atlassian.net/browse/PS-285
https://topcoder.atlassian.net/browse/CORE-566

Text changes for Wipro and "Activity Feed" to "Opportunities"

---

src/shared/containers/GigsPages/index.jsx

https://topcoder.atlassian.net/browse/TOP-2194

TOP-2194 bring back main viewport

---

src/shared/components/Gigs/GigApply/index.jsx
src/shared/components/Gigs/GigDetails/index.jsx

https://topcoder.atlassian.net/browse/PM-337

PM-337 update gig work email

---

src/shared/components/Contentful/Article/Article.jsx
src/shared/components/Gigs/GigApply/index.jsx
src/shared/components/TopcoderHeader/Auth/index.jsx
src/shared/components/tc-communities/AccessDenied/index.jsx
src/shared/components/tc-communities/Footer/index.jsx
src/shared/components/tc-communities/Header/index.jsx
src/shared/containers/Dashboard/index.jsx
src/shared/containers/challenge-detail/index.jsx
src/shared/containers/tc-communities/Loader.jsx
src/shared/utils/tc.js

https://topcoder.atlassian.net/browse/PM-197 - Cross-Site Scripting: Poor Validation (17 issues)
To avoid user input via url, when redirecting away from the platform (eg. to login / to social platforms), set the return url as location.origin + location.pathname. In theory this should avoid any unknown user input as paths are predetermined and can not be considered untrusted user input.

PM-197 - XSS poor validation error handling

---

.circleci/config.yml
src/server/index.js
src/server/services/communities.js

- Used promised based fs functions for getting file content
- Also checking for file size and checking if the path exists

PM-199, PM-209 Denial of service fix

---

src/shared/containers/Dashboard/index.jsx

- Removed thrive and blog feed from home page. They are already removed in the backend as they are deprecated.

PROD-4454: Fix home page not loading

---

src/server/services/communities.js

- Used promisify instead of sync file read API which should resolve path manipulation issue.

fix(PM-716): used promisify instead of sync file read API

---

src/shared/components/Contentful/Article/Article.jsx
src/shared/components/Contentful/MemberTalkCloud/MemberTalkCloud.jsx
src/shared/components/challenge-listing/placeholders/ChallengeCard/index.jsx
src/shared/utils/secureRandom.js

- Used crypto random instead of math random as it is not secured.

fix(PM-717): use crypto random instead of math random

---

config/default.js
src/shared/components/SubmissionPage/FilestackFilePicker/index.jsx

https://topcoder.atlassian.net/browse/PM-967 - Topgear - Submission URL validation

PM-967 - check topgear urls

---

src/shared/components/SubmissionPage/Submit/index.jsx
src/shared/components/SubmissionPage/Submit/styles.scss

- Updated submission text for topgear challenges

fix: updated submission text for topgear challenges

---

src/shared/components/SubmissionPage/Submit/index.jsx
src/shared/components/SubmissionPage/Submit/styles.scss

- Fix styles in submission page

fix: styles in submission page

---

.github/workflows/code_reviewer.yml

Add another domain to the Topgear challenges - allowed submissions urls

PROD - Topgear challenges - Submissions urls

---

src/shared/components/challenge-detail/Registrants/index.jsx

https://topcoder.atlassian.net/browse/PM-1055
Previously, the sorting failed when getFinal() returned undefined. Now we fallback to getSubmissionDate() in case of anonymous user
Fixes PM-1055

Fix(registrants): sort by submitted date correctly

---

.github/workflows/code_reviewer.yml

https://topcoder.atlassian.net/browse/PM-1055
https://topcoder.atlassian.net/browse/PM-1192

[PROD RELEASE] - Bug fixes

---

src/shared/components/challenge-listing/CopilotOpportunityCard/index.jsx

- Fixed canceled status color
Ticket link - https://topcoder.atlassian.net/browse/PM-1311

fix(PM-1311): canceled status color

---

src/shared/components/challenge-listing/Filters/FiltersPanel/index.jsx

- dont show more filters button for copilots bucket
Ticket link - https://topcoder.atlassian.net/browse/PM-1316

fix(PM-1316): dont show more filters button for copilots bucket

---

src/shared/services/copilotOpportunities.js
src/shared/utils/challenge-listing/sort.js

Fixes the sorting on copilot opportunities page
Introduced a new param in API which will make the response ungrouped based on status.
This resolves the sorting conflicts
Also fixed a small bug with opportunity title sort

fix: sorting on copilots opportunity PM-1314

---

src/shared/actions/page/review-opportunity-details.js
src/shared/components/ReviewOpportunityDetailsPage/FailedToLoad/index.jsx
src/shared/components/ReviewOpportunityDetailsPage/FailedToLoad/styles.scss
src/shared/components/ReviewOpportunityDetailsPage/Header/PhaseList/index.jsx
src/shared/components/ReviewOpportunityDetailsPage/index.jsx
src/shared/components/challenge-listing/ReviewOpportunityCard/index.jsx
src/shared/containers/ReviewOpportunityDetails.jsx
src/shared/reducers/page/review-opportunity-details.js
src/shared/services/reviewOpportunities.js

Migrates review opportunity details page to v6 review api
Adds code from topcoder-react-lib to get details of the review opportunity (getDetails)
Also fixes the frontend to work with the new API response.
For an anonymous user, we are showing the review opportunity details page. On clicking the Apply for Review button, user is redirected to login, where if they're a reviewer, the normal flow occurs. And, if they're not a reviewer, we show them an error message saying Permission denied. 
This message needs a link to a page where the user can go apply to be a reviewer - LMK of the url

migrate: review opportunity details page to v6 review API
